### ISSUE TITLE
Compiling csproj with xbuild - dependent on source file location?

### ISSUE THREAD

**Issue by anton-christensen** [bridgedotnet/Bridge#1028]
I get the following error when running Bridge.Builder.exe on my compiled project.
I have attached a working example and the example in which i get the error
[test_error.zip](https://github.com/bridgedotnet/Bridge/files/158733/test_error.zip)
[test_working.zip](https://github.com/bridgedotnet/Bridge/files/158734/test_working.zip)

The difference is in the one in which I get the error, the sourcefile is placed inside a src/ directory instead of the same level as the .csproj file.
I wouldn't have expected Bridge.Build to be dependent on my source files anyway...

```
...
...
Bridge.Builder.Console: Info 2016-03-04T14:50:09:952 Inspecting types...
		Bridge.Builder.Console: Info 2016-03-04T14:50:09:953 Inspecting types done
		Bridge.Builder.Console: Info 2016-03-04T14:50:09:953 Creating emitter...
		Bridge.Builder.Console: Error 2016-03-04T14:50:09:956 Error: exception level: 0 - Object reference not set to an instance of an object
		Stack trace:
		  at Bridge.Contract.BridgeTypes.InitItems (IEmitter emitter) <0x41a1a920 + 0x001d0> in <filename unknown>:0 
		  at Bridge.Translator.Emitter..ctor (IDictionary`2 typeDefinitions, Bridge.Contract.BridgeTypes bridgeTypes, System.Collections.Generic.List`1 types, IValidator validator, IMemberResolver resolver, System.Collections.Generic.Dictionary`2 typeInfoDefinitions, ILogger logger) <0x41a1a570 + 0x001af> in <filename unknown>:0 
		  at Bridge.Translator.Translator.CreateEmitter (IMemberResolver resolver) <0x41a1a470 + 0x000b3> in <filename unknown>:0 
		  at Bridge.Translator.Translator.Translate () <0x41995ad0 + 0x006ce> in <filename unknown>:0 
		  at Bridge.Builder.Program.Main (System.String[] args) <0x4198bd70 + 0x012d3> in <filename unknown>:0 
```

### Steps To Reproduce
I run ubuntu 14.04 and build the project by running the xbuild command, from the mono project, in the directory with the .csproj file.

**Comment by fabriciomurta** [comment]
Hello @anton-christensen, I was just creating an issue to reflect a forum thread we have also pointing to this problem!
The forum thread is [The new version 1.11.1 doesn't compile in Xamarin Studio](http://forums.bridge.net/forum/community/help/1746), and I'll reference it to this thread.

That said, we're already working on the solution of this issue and hope to fix this soon.

The actual issue is that we recently changed NuGet packaging structure and no longer merge the `Bridge.Builder.dll` in the `tools` directory of the package with its dependencies.

Seems that `msbuild` looks for the libraries in the same directory and just leaving them loose works just fine. `xbuild` in turn does not look for additional libraries on the actual DLL directory thus does not find these references.

I am afraid this is rather a `Mono` bug as it was supposed to behave as Microsoft's `msbuild`. I hope we can find a solution that works both on MSBuild & Mono to ensure a portable result.

Thanks for reporting the issue too!

**Comment by fabriciomurta** [comment]
About your comment

> I wouldn't have expected Bridge.Build to be dependent on my source files anyway...

It depends on your source files -and- the built assembly before it can effectively build the code. The source files are needed to [build the syntax tree](https://github.com/bridgedotnet/Bridge/blob/master/Compiler/Translator/Translator/Translator.InspectAssembly.cs#L247-L312).

**Comment by fabriciomurta** [comment]
Another update: your error is not the same as the forum thread I've mentioned above, you are not using NuGet packages at all. Seems you are basing your project from the VSCode example. Am I right?

**Comment by anton-christensen** [comment]
That is true. I used the builder.sh file to discern how to use bridge builder directly instead if using the target file in the nuget package

**Comment by fabriciomurta** [comment]
Hello! How have you created your .csproj file?

You can install the NuGet package in both Visual Studio (on Windows) or on XamarinStudio (linux). Additional step while using XamarinStudio is to check 'Do not reference mscorlib.dll' on the project's Build options.

The correct form to use `Bridge.Builder.exe` while using a .csproj file also, is to use the commandline argument `-p <project>.csproj` so it loads the paths for the libraries and source files accordingly.

This is in fact broken though, and I will create an issue and relate to this one. :)

For now, you can use the NuGet (with UsingTask) on linux to build on mono using .csproj projects.

**Comment by fabriciomurta** [comment]
Considering you didn't have a .csproj file and provided all source files are inside the directory builder is going to be run, to build from commandline (without using the projected `-p` commandline flag) you should add the `-recursive` commandline option to the exec line in order to search the source files recursively.

This is how it would work:
```
 <Exec Command="mono build\Bridge.Builder.exe -lib $(OutputPath)$(AssemblyName).dll -recursive"/>
```

Notice: your sample solutions call the executable directly instead as being an argument to the `mono` command. Probably your solution works on Windows, but it would probably be using MS .NET instead of Mono for the Bridge part the way you are calling it then.

**Comment by LeonidVeriga** [comment]
We are closing the issue. Should you have any further questions on this topic please reopen the issue.
