### ISSUE TITLE
Char (s) give incorrect types when stored as objects.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1292]
### Expected

Bridge.Char
### Actual

Bridge.Int32
### Steps To Reproduce

``` csharp
public class App
{
    [Ready]
    public static void Main()
    {
        object v = 'a';
        Console.WriteLine(v.GetType().FullName);
    }
}
```

[Sample](http://live.bridge.net/#4750815d70802a9a513a1b99d52350b9)

**Comment by geoffreymcgill** [comment]
Related to #1248, #1293 and #1184.

I think the only way around this issue is to implement JavaScript type wrappers for all the .NET types. Fairly easy to do, but downside is a performance impact. We will be implementing in a future release, but this is going to take a while before it's available. After Bridge 1.15 sometime.

**Comment by michaelcheers** [comment]
@geoffreymcgill, You only need to put a wrapper around .NET classes when casted to object.
```csharp
int v = 3;
Console.WriteLine(v.GetType().FullName);
```
can compile to:
```javascript
var v = 3;
console.log(Bridge.getTypeName(Bridge.Int32));
```
but
```csharp
object v = 3;
Console.WriteLine(v.GetType().FullName;
```
would compile to:
```javascript
var v = new Bridge.Int32(3);//or some way of wrapping the type
console.log(Bridge.getTypeName(Bridge.getType(v));
```

**Comment by iskiselev** [comment]
In JSIL we wrap native types only when IL box them.

**Comment by LeonidVeriga** [comment]
@michaelcheers, @iskiselev,

Thanks for suggestions guys.
