### ISSUE TITLE
Fields cannot be named __proto__

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1344]
### Expected
```
True
```
### Actual
```javascript
false
```
### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#344ddb787193fdf18fa2ac95f1d97afb)
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public string __proto__;
    
    public App ()
    {
        __proto__ = "hello world";
        Console.WriteLine(__proto__ == "hello world");
    }
    
    // Use the [Ready] attribute to automatically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
        App app = new App();
    }
}
```

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers,

Can you describe a scenario you would need to use `__proto__` directly.

If you just need a property named `__proto__` then we would include this name into reserved property names list. Otherwise, we could support `__proto__` on `Object` class level (including method `Object.getPrototypeOf()`).

**Comment by michaelcheers** [comment]
I think we should include it in the reserved property names list.

**Comment by LeonidVeriga** [comment]
Related #1257

**Comment by michaelcheers** [comment]
I think this is my fault but it still doesn't work.
