### ISSUE TITLE
Extension method bug

### ISSUE THREAD

**Issue by dmitsov** [bridgedotnet/Bridge#1436]
Hello, while working with bridge.net I came across a curious bug. When we are translating the code bellow from c# to js with bridge we get the error: 

```
The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

We defined our own **BinaryReader** and **BinaryWriter** classes in order to complete our projects. This isn't the first time we had this issue but we found a workaround by using extension methods like regular ones.

```C#
public static class BinaryReaderExt
{
	public static string ReadAlignedString(this BinaryReader self, int length, int a = sizeof(int))
	{
		string s = Encoding.ASCII.GetString(self.ReadBytes(length));
		s = s.TrimEnd('\0');
		return s;
	}

	public static string ReadAlignedPrefixedString(this BinaryReader self, int a = sizeof(int))
	{
		int length = NetworkUtility.Align(self.ReadInt32(), a);
		BinaryReader reader = self;
		return self.ReadAlignedString(length, a);
	}
}
```

**Comment by geoffreymcgill** [comment]
Hi @dmitsov - Can you provide a http://live.bridge.net sample demonstrating the scenario?

**Comment by vladsch** [comment]
Hi,

First, `sizeof` operator is not supported by Bridge
Second, such issue can occur if you add reference to assembly which is compiled with standard .NET core library. Bridge supports assemblies which are compiled with Bridge core library only. I guess it is the reason because I see `Encoding.ASCII.GetString` and `BinaryReader` which is not supported (and absent) in Bridge core

**Comment by LeonidVeriga** [comment]
Hi @dmitsov,

We are closing this issue. If you have questions feel free to reopen.
