### ISSUE TITLE
Bridge Live is not working with using System

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1532]
### Expected

Work

### Actual

Doesn't.

### Steps To Reproduce

Click this [link](http://live.bridge.net/#4c16f313f9441e4078813d2212ee8a0e).
```

**Comment by geoffreymcgill** [comment]
If you declare a `using` statement, the compiler expects that you'll define the `namespace` as well. For example:

http://live.bridge.net/#5d017e4c6dd4c52f400e315002e1563e

Hope this helps.

**Comment by michaelcheers** [comment]
@geoffreymcgill, Could you give a better error message then?

**Comment by geoffreymcgill** [comment]
The issue lies within Live Bridge, and not within the Bridge Compiler. 

Basically the problem is Live Bridge includes simple logic to determine if the code sample should be wrapped in namespace template (or not).

I believe the logic applied is:

1. If the sample does not start with `using`, then wrap the sample provided in a default namespace template.
2. If the sample starts with `using`, then pass that code directly to the compiler. 

So, the problem with the original sample you provided is that it's not a compilable C# code sample. It would require a namespace declaration. Because the code sample starts with `using`, the sample is **not** automatically wrapped in a namespace template. 

By just adding something ahead of the `using` statement, the sample will be wrapped in a template.

**Example**

http://live.bridge.net/#ebb217df5164045bffee9dd22aa94fb4

```cs
// test
using System;

/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public static void Main()
    {
    }
    static string @string;
}
```

I admit the namespace template logic test is pretty "dumb", and could certainly be improved. Maybe a simple regex could be used to determine if a `namespace` has been set in the supplied code sample.

The [full source](https://github.com/bridgedotnet/Live) for Live Bridge is available in GitHub. If anyone wants to improve the app, we really appreciate your interest and involvement.
