### ISSUE TITLE
Use self or window instead of Bridge.global.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1553]
### Expected

Use window.
### Actual

Uses Bridge.global,
### Steps To Reproduce

[Live Bridge](http://live.bridge.net/#ac3c58636ccd0ea08ddce3c74db6bf04)

``` csharp
public class App
{
    public static void Main()
    {
        Global.ToDynamic().fetch("info.json");
    }
}
```

**Comment by geoffreymcgill** [comment]
But this would be making an assumption that there is a `window` object for the environment.

You could change your code to:

```c#
Window.ToDynamic().fetch("info.json");
```

**Comment by michaelcheers** [comment]
@geoffreymcgill, then why not use self.

**Comment by geoffreymcgill** [comment]
@michaelcheers, can you provide more explanation? I'm not sure what you're referring too re self.

**Comment by michaelcheers** [comment]
@geoffreymcgill, self is more well known than Bridge.global. It's the global object. [Live Bridge](http://live.bridge.net/#0784c227227bcc669c7390bccb66f26b)

**Comment by geoffreymcgill** [comment]
My understanding of `self` is that it's basically a pointer to the `window` object. Essentially an alias of `window`. 

Your Live Bridge sample works, because in this context `Bridge.Global` returns an instance of `window`, and `window === self`. But this only works because `window` is available in the environment.

We can add a **Self** class to **Bridge.Html5**, which inherits from **Window**, but I still don't think `window` should be considered a consistent _global_ object across platforms.
