### ISSUE TITLE
"Unable to determine output path" - Exception is thrown if another solution platform is added in Visual Studio

### ISSUE THREAD

**Issue by Kafkalasch** [bridgedotnet/Bridge#1605]
Hello,

if I add another Solution platform in Visual Studio via the Configuration Manager (e.g. "x64") and try to build the project I get an "Unable to determine output path"-Exception thrown in Bridge/Compiler/Translator/Translator/Translator.ProjectReader.cs at line nr 158

**Comment by vladsch** [comment]
Hi,

How csproj file looks after adding new configuration? Can you post here content of project file? We need ProjectGroup sections only

**Comment by Danielku15** [comment]
I have a similar problem and was able to find the root cause of the issue:

**Comment by Danielku15** [comment]
I have a similar problem and was able to find the root cause of the issue:
https://github.com/bridgedotnet/Bridge/blob/master/Compiler/Translator/Translator/Translator.ProjectReader.cs#L170

If you have multiple configurations with similar names the check done in GetOuputPath is not covering all cases. 

Imagine you have 2 build configurations: Debug and DebugWithPostBuild or if you have, like Kafkalasch multiple Configurations you will have Debug|AnyCpu and Debug|x64 in your project file: 

```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DebugWithPostBuild|AnyCPU'">
    <OutputPath>bin\DebugWithPostBuild\</OutputPath>
  </PropertyGroup>

or 

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\DebugWithPostBuild\</OutputPath>
  </PropertyGroup>
```
A simple contains check will return multiple nodes which then reulsts in a "Unable to determine output path".
