### ISSUE TITLE
run field intializers on ready time

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1694]

**Comment by vladsch** [comment]
Please provide more details

**Comment by michaelcheers** [comment]
Like 
```csharp
public static HTMLInputElement cool = Document.GetElementById<HTMLInputElement>("input");
```
doesn't work because the html hasn't been loaded yet.

**Comment by vladsch** [comment]
It is not Bridge defect, it is developer error. Field initialization occurs during first access of the class
So, you need first access in ready handler or make explicit initialization

**Comment by geoffreymcgill** [comment]
Yes, I believe this is not working because the field is initialized too soon in the document lifecycle. The `. GetElementById` must happen after the document is loaded in the browser. At the point this code is executed, the `input` Element does not exist in the document.

One potential work-around (I haven't tested) would be loading your projects `<script>` .js file at the end of the page, somewhere just before the closing `</body>` tag. Once the browser reaches this point, the html should have been loaded and the Element should be available... if it's hardcoded in the markup. 

Hope this helps.
