### ISSUE TITLE
AjaxOptions BeforeSend's jqXHR has no 'SetRequestHeader' method

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#179]
This issue was identified while attending this forum post:
[Jquery Ajax call - with basic Authentication](http://forums.bridge.net/forum/community/help/168)

`AjaxOptions.BeforeSend` property's prototype is:
`System.Func<Bridge.jQuery2.jqXHR,object,boot>`

According to [this stackoverflow](http://stackoverflow.com/questions/14010851/set-request-header-jquery-ajax) discussion, `jqXHR` should accept a `SetRequestHeader(string, string)` call.

`jqXHR` class in turn does not have method stub for `SetRequestHeader`.
This method definition was found in `Bridge.Html5.XMLHttpRequest`. The signature is exactly as used in the stackoverflow discussion above.

Trying to just `jqXHR.ToDynamic()` triggers the bug #178.

With that said, what would be best to address this issue and improve user experience:
a. Change `AjaxOptions.BeforeSend` type to `Func<Bridge.Html5.XMLHttpRequest,object,bool>`?
b. Change `Bridge.jQuery2.jqXHR` to inherit from `Bridge.Html5.XMLHttpRequest`?
c. Implement the method stubs to `Bridge.jQuery2.jqXHR`?
d. Just fix #178 and set it as a dynamic type, as the parameter may have unexpected/custom properties?
e. Your suggestion here: _____________________________________

**Comment by fabriciomurta** [comment]
Assigned to @vladsch for technical viability feedback. @geoffreymcgill might also be interested in suggesting the best fix in this scenario.

**Comment by DaniilVeriga** [comment]
For references - [jqXHR documentation](http://api.jquery.com/jQuery.ajax/#jqXHR).

The **b** option would be good if jqXHR should not inherit the Deferred class as well:) The problem is that jqXHR is a XMLHttpRequest and a Deferred at the same time. No problem in JavaScript, but a little bit problematic in C#. So, we have to inherit from the only class and repeat/stub out the methods of the other class. XMLHttpRequest has much more members than Deferred. So, we will probably end up with inheriting XMLHttpRequest and repeat lost Deferred API. I don't quite like repeating, but do we really have any other option?

**Comment by DaniilVeriga** [comment]
Inherited jqXHR from XMLHttpRequest and repeated the Deffered API methods.

**Comment by DaniilVeriga** [comment]
Bridge.jQuery 2.1.0 has been released with the fix.
