### ISSUE TITLE
Regex initialization fails when contains "@\<" string

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1934]
Reported on the [forum](http://forums.bridge.net/forum/bridge-net-pro/bugs/2866-open-1934-regex-initialization-fails-when-regex-cotnains-string-regression-in-v15-2-0).

### Expected
Regex should work with no error and show `IsMatch: True` in console output.
[.Net Fiddle](https://dotnetfiddle.net/ZJ5DSC)

### Actual
JS error
```js
`Unrecognized escape sequence \<.
 /resources/js/bridge/bridge.js?15.2.0.0:21725
```

### Steps To Reproduce

[Deck](http://deck.net/4c677327593f57d7129ad61672ef9b87)

```cs
public class Programm
{
    private static Regex r = new Regex(@"\<\>");
    public static void Main()
    {
        Console.WriteLine("IsMatch: {0}", r.IsMatch(@"<>"));
    }
}
```

**Comment by AndreyChechel** [comment]
A fix has been submitted. Since Unicode blocks/categories are not supported now (#1823), the fix guarantees that at least [Basic Latin](https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block)) characters should work as expected.

By the way, some characters specified in the example above do not require escaping. This could be easily checked using `Regex.Escape` method. Thereby, as a possible workaround, those characters can be used "as is" without escaping.
