### ISSUE TITLE
[LINQ] OfType<double>() gets different results compared to .Net

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#218]
```C#
using Bridge;
using Bridge.Html5;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            object[] numbers = { null, 1.0, "two", 3, "four", 5, "six", 7.0 };
            var doubleNumbers = numbers.OfType<double>().ToArray();
            Console.Log(doubleNumbers);
        }
    }
}
```
Actual result: [1, 3, 5, 7]
.Net result: [1.0, 7.0]

**Comment by vladsch** [comment]
It is impossible to fix it because javascript has Number type only and if there is no decimal part (or it is equals 0) then 1 and 1.0 looks the same in javascript. Also type `double` is emitted like `Number`
So, all numbers in javascript is one type
I will close the issue due impossibility to fix it, it is javascript feature
