### ISSUE TITLE
Intersection type

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#2192]
Since #1976 introduced a new **Union** type commonly used in TypeScript, it's worth also creating another type - [Intersection](https://www.typescriptlang.org/docs/handbook/advanced-types.html). Whereas **Union** and **Intersection** types are closely connected, and moreover, they are likely to be implemented identically in Bridge - they are not the same thing, and they have different purpose under the hood.

Variable of `Union<T1, T2>` type means that it can hold value of either `T1` or `T2` type. As for variable of `Intersection<T1, T2>` type, it contains fields and functions both from `T1` and `T2` types (or, what is the same, `T1` extended with `T2`).

I created an example showing how **Intersection** type can be used. The implementation here is the same as for **Union** type, nevertheless I suggest having a separate type for **Intersection**, since it has different contract and different usage.

The example has not implementation of **Intersection** constructor accepting merging variables. In my opinion it's also worth having it in place to simplify initialization of such types. Probably, it can be done within a separate feature request. 

### Output in Bridge Console

```
John Doe 
{"name":"John Doe # 1","stringify":true}
John Doe # 2
[object Object]
```

### Example

http://deck.net/cec417ec257e3d515556346f794c2c4e

```cs
public class Program
{
    public static void Main()
    {
        var person1 = GetLoggablePerson("John Doe #1", true);
        Console.WriteLine(person1.Item1.Name);
        person1.Item2.Log();
        
        var person2 = GetLoggablePerson("John Doe #2", false);
        Console.WriteLine(person2.Item1.Name);
        person2.Item2.Log();
    }

    // Consider the GetLoggablePerson function as external one:
    public static Intersection<Person, Loggable> GetLoggablePerson(string name, bool strigifyWhenLogged)
    {
        var person = new Person(name);
        var loggable = new Loggable(strigifyWhenLogged);
        
        //@ person.log = loggable.log;
        //@ person.stringify = loggable.stringify;
        
        return person;
    }

    public class Person
    {
        public string Name;
        public Person(string name)
        {
            Name = name;
        }
    }

    public class Loggable
    {
        public bool Stringify;
        public Loggable(bool stringify)
        {
            Stringify = stringify;
        }
        
        public void Log()
        {
            if(Stringify)
            {
            	var str = JSON.Stringify(this);
            	Console.WriteLine(str);
            }
            else
            {
                Console.WriteLine(this);
            }
        }
    }
    
    [External]
    [IgnoreGeneric]
    [IgnoreCast]
    [Name("Object")]
    public class Intersection<T1, T2>
    {
        public extern T1 Item1
        {
            [Template("{this}")]
            get; 
        }
        
        public extern T2 Item2 
        {
            [Template("{this}")]
            get; 
        }

        protected extern Intersection(T1 arg1, T2 arg2);

        public static extern implicit operator Intersection<T1, T2>(T1 t);

        public static extern implicit operator Intersection<T1, T2>(T2 t);
        
        public static extern explicit operator T1(Intersection<T1, T2> value);

        public static extern explicit operator T2(Intersection<T1, T2> value);
    }
}
```

**Comment by ProductiveRage** [comment]
Is there a lot of value in this feature request, considering how it would have to be implemented in C#? For TypeScript, I can see a lot of value because members from either type may be accessed directly - eg. (to continue your example):

```
// TypeScript
console.log(person1.Name);
person1.Log();
```

The TypeScript compiler knows that "person1" has the Name property and the "Log" method and there is no potential for nasty runtime errors to crop up.

However, in C#, you would need to do the following (also from your example) -

```
// C#
Console.WriteLine(person1.As<Person>().Name);
person1.As<Loggable>().Log();
```

This _does_ have the potential for runtime failure since there is no way for the compiler to ensure that person1 may be cast to whatever the type "T" passed to As<T> is. It would be possible to write code such as

`person1.As<SomeOtherType>().DoSomething();`

.. that will fail at runtime.

Since TypeScript and Bridge.NET are about bringing type safety to JavaScript, in order to avoid runtime errors (granted that's not _all_ that TypeScript and Bridge are for but it is a key quality of both - the potential for static analysis catching programmer errors) then I'm not sure how much sense it makes to introduce a type like this that won't support type safety (since there can be no guarantees made about the type passed to the "As" call).

The only thing I can think of is that possibly this could make it possible to write more descriptive interfaces to existing libraries? If a library was written in TypeScript and has a TypeScript definition that uses Intersection types, would having the type available in Bridge make it easier for C# code to communicate with the library? Even if this was the case, it would probably be easier to write a Bridge binding to the library that used types that were better suited to C# (for example, a specific ILoggablePerson interface would exist in the binding so that a C# reference to "person1" _could_ retrieve the "Name" property or call the "Log" property). This would require defining more types in the Bridge binding (rather than using a generic Intersection type) but the type safety in C# would be much stronger.

**Comment by AndreyChechel** [comment]
@ProductiveRage, thanks for sharing your thoughts on this topic. I agree that Bridge must provide strong type safety where possible. And it looks like that could be supported for the given scenario as well. 

Please check the updated example above. I've added `Item1` and `Item2` properties with `[Template]` attributes applied. This will elliminate necessity of casting **Intersection** variable and will allow to access members declared with proper type specified.

I like your idea to write more descriptive interfaces to support JavaScript and TypeScript libraries in Bridge bindings. The only concern here is that this process may require significant efforts, especially, for the libriaries having a big range of entities. It may be even more complicated when dependency graph is not a plain one.

**Comment by ProductiveRage** [comment]
I think that the "Item1", "Item2" approach is much more robust. A good improvement.

There has been some investigation in the past into building something that can read TypeScript interfaces and generate Bridge bindings automatically (the Bridge Team started one here: https://github.com/bridgedotnet/Retyped).

Once one of these becomes more mature, it shouldn't be too difficult to have it automatically create "combined interfaces" (or "more descriptive interfaces", as I referred to them earlier). Then there would be no additional work for anyone to do by hand _and_ you would have access to objects where you could call the methods directly -

```
// C#
Console.WriteLine(person1.Name);
person1.Log();
```

And that might be the best of both worlds!

However, they may still be times when it's preferable to have the flexibility of an Intersection type (and I'm much more adverse to it with your recent change :)
