### ISSUE TITLE
Setting dynamic delegates can be hard

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2209]
It is a bit inconvenient to set delegate properties on dynamics.
It would be nice to be able to not have to declare a variable especially.

http://deck.net/6e5cb056dd1bc81299a008047cfec68a

```csharp
public class Program
{
    public static void Main()
    {
        dynamic element = Document.CreateElement("input");
        Action<dynamic> OnInput = Program.OnInput;
        element.oninput = OnInput;
    }
    
    public static void OnInput (dynamic @event)
    {
        
    }
}
```

**Comment by ProductiveRage** [comment]
If you use the generic Document.CreateElement method then things become much simpler because you don't need to deal with dynamics anywhere.

To demonstrate, I've changed your code to the following -

```
public class Program
{
    public static void Main()
    {
        var element = Document.CreateElement<HTMLInputElement>("input");
        element.OnInput = OnInput;
        
        Document.Body.AppendChild(element);
    }
    
    public static void OnInput(Event<HTMLInputElement> ev)
    {
        Console.WriteLine($"OnInput: '{ev.CurrentTarget.Value}'");
    }
}
```

(May be previewed at [http://deck.net/a1eaca198386a6b4571b6f5fdac79ebf](http://deck.net/a1eaca198386a6b4571b6f5fdac79ebf)).

Calling "Document.CreateElement<HTMLInputElement>" means that "element" is an instance of "HTMLInputElement" (and so may be defined using "var" instead of "dynamic).

Also, because "element" is an "HTMLInputElement", its "OnInput" property is of type "Action<Event<HTMLInputElement>>" and so the "CurrentTarget" property is of type "HTMLInputElement" and so you can access the "Value" string in a type-safe manner (so the "OnInput" method argument is no longer dynamic).

Depending upon how complicated your "OnInput" method is going to be, you could consider inlining that so that you can rely on type inference to avoid having to write out "Event<HTMLInputElement>" as the argument type - eg.

```
public class Program
{
    public static void Main()
    {
        var element = Document.CreateElement<HTMLInputElement>("input");
        element.OnInput = ev =>
        {
	        Console.WriteLine($"OnInput: '{ev.CurrentTarget.Value}'");
        };
        
        Document.Body.AppendChild(element);
    }
}
```

**Comment by vladsch** [comment]
Also, variable is not required. Just use cast 
`element.oninput = (Action<dynamic>)Program.OnInput;`

It is C# requirement, not Bridge

**Comment by geoffreymcgill** [comment]
Reductio ad absurdum:

http://deck.net/2cdc331792fce2376150355461545514

```cs
public class Program
{
    public static void Main()
    {
        Document.Body.AppendChild(new HTMLInputElement
        {
            OnInput = ev =>
            {
                Console.WriteLine($"OnInput: '{ev.CurrentTarget.Value}'");
            }
        });
    }
}
```

**Comment by michaelcheers** [comment]
@Zaid-Ajaj that's what I suggest they add
