### ISSUE TITLE
[Core] Arithmetic operation differences compared to .Net

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#223]
I'm not sure whether it is a feature or bug, and what we can do with that.

```C#
using Bridge;
using Bridge.Html5;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            var number1 = (double)11 / 3;
            Console.Log("       Actual: " + number1);
            Console.Log(".Net expected: 3.66666666666667");

            double number2 = 1.7 * 2.3 * 1.9 * 4.1 * 2.9;
            Console.Log("       Actual: " + number2);
            Console.Log(".Net expected: 88.33081");
        }
    }
}
```
Actual and expected results:
```
           Actual: 3.6666666666666665
    Net expected:  3.66666666666667

           Actual: 88.33080999999999
    Net expected:  88.33081
```

**Comment by vladsch** [comment]
It is related with that issue
https://github.com/bridgedotnet/Bridge/issues/172

**Comment by DaniilVeriga** [comment]
If use 1.8.0 and `decimal` instead of `double`, then it produces:

```
       Actual: 3.6666666666666666666666666667
.Net expected: 3.66666666666667
       Actual: 88.33081
.Net expected: 88.33081
```

@vladsch, @LeonidVeriga, @geoffreymcgill, do you think the issue might be closed?

Yes, the issue still exists with `double`. But is it going to be fixed with `double` ever?

Although, even using `decimal`, the first test fails - still not the same results. Again, is it going/needed to be fixed ever?

**Comment by LeonidVeriga** [comment]
I think the issue should be closed. For precise calculations we should use `decimal`.

**Comment by erik-kallen** [comment]
I don't think the problem is in the calculation, but in the print. The actual value is most likely the same, just that JS prints it with less decimals

**Comment by DaniilVeriga** [comment]
Interesting. So, you assume that the actual value is `3.66666666666667`, but on `console.log(value)` call it is printed (internal `.toString()` call?) as `3.66666666666667`. Do I understand you correctly?

Hmm, is there any way to determine the actual value?:) I mean any alternative way rather than printing.

**Comment by geoffreymcgill** [comment]
Unit Test for equality?

**Comment by LeonidVeriga** [comment]
For me the code executed in .Net
```
   var d1 = 11m;
   var d2 = 3m;
   decimal d = d1 / d2;
```
and its transpiled JavaScript analog executed in browser
```
   var d1 = Bridge.Decimal(11.0);
   var d2 = Bridge.Decimal(3.0);
   var d = d1.div(d2);
```
 give the same results
 `3.6666666666666666666666666667`
 `3.6666666666666666666666666667`

**Comment by DaniilVeriga** [comment]
Thank you for the follow-up, Leonid. I realized that I compared the .NET result for double values with JavaScript result for decimal values. If compare results for decimal values, they are identical. Sorry for bothering.
