### ISSUE TITLE
Using list<string> in typescript

### ISSUE THREAD

**Issue by anatsegev** [bridgedotnet/Bridge#2264]
Hi,

My project defines some class that should get an IEnumerable<string> as constructor parameter:

```cs
public MyClass(IEnumerable<string> queryParameters = null)
}
```

I've generated typescript definition files to my bridge.net project,
and then reference these files in a typescript file.

According to the d.ts files the constructor of my class expects to get 

```ts
queryParameters: System.Collections.Generic.IEnumerable$1<string>
```

The problem is that when I try in typescript to create a list of strings like this:

```ts
var myQueryParameters = new (System.Collections.Generic.List$1(String))();
```

and pass it to MyClass constructor it complains that it is not assignable to 

```ts
System.Collections.Generic.IEnumerable$1<string> (string in small letters)
```

And if I do it like that:

```ts
var myQueryParameters = new (System.Collections.Generic.List$1(string))();
```

It also complains.

How do I create a list of strings?

**Comment by geoffreymcgill** [comment]
Hi @anatsegev – Can you link to a [Deck.NET](http://deck.net) sample that demonstrates this scenario?

**Comment by vladsch** [comment]
Yes, there is an issue with primitive javascript classes. TypeScript considers `string` and `String` as different types
We will fix it next release. Please note that you have add generic argument to List because it is generic type
The following construction should work in next release
`new Demo.MyClass(new (System.Collections.Generic.List$1<string>(String))())`
