### ISSUE TITLE
Visual Studio Code intellisense and ASP.NET 5

### ISSUE THREAD

**Issue by antonmes** [bridgedotnet/Bridge#238]
I trying to get intellisense to work with OmniSharp (VSC / sublime).. dnu restore fails with "Unable to locate Bridge.NET". Do you have plans to provide coreclr packages and some better way to use with asp.net 5, for example through a service pipeline?
As a workaround for VSCode/Demo example i use Brige.NET as submodule with project.json file https://github.com/antonmes/Demos/tree/submodule/VSCode
I'm not quite sure about pushing project.json to Brige but as I figured out it does not conflict with .sln file and can be added safely.

**Comment by fabriciomurta** [comment]
Sorry for taking so long. I'm finally looking at this issue and hope to be able to return soon with feedback!

**Comment by fabriciomurta** [comment]
Hello @antonmes!

Are you creating your project on Visual Studio and then migrating it to your *nix with VSCode+DNX? DNU restore is run to get back the NuGet packages your project is supposed to pull once the project is built (in the absence of the package), right?
The actual package name would be just 'Bridge' and not 'Bridge.NET'. That could be a reason `dnu restore` is failing for you.

**Comment by fabriciomurta** [comment]
Here's an example of a working project.son which will correctly pull NuGet packages off NuGet servers.
```
{
 "version": "0.0.1-alpha-*",
 "code": ["Demo.cs"],
 "dependencies": {
  "Bridge":"1.5.0"
 },
 "frameworks": {
  "dnx50": {
   "dependencies": {
   }
  }
 }
}
```
I just add this project.json to the 'Demo' project (the same you forked) and then I get Intellisense working correctly. In fact, the problem was essentially you using `Bridge.NET` instead of just `Bridge` as the project name.

I will soon update the repository with this project file, removing its committed .DLLs (they shouldn't be committed in the first place), and then I update this once again.

**Comment by antonmes** [comment]
@fabriciomurta thanks! can't remember the name i used, but now intellisense is working.

**Comment by antonmes** [comment]
Are you talking about removing `Bridge.Builder.exe` from Demo project? i tryed to use Bridge.Builder.dll from nuget with mono and coreclr/dnx, but they both failed.

```
$dnx /Users/toxa/.dnx/packages/Bridge/1.5.0/tools/Bridge.Builder.dll run
'Bridge.Build' does not contain a static 'Main' method suitable for an entry point
```

Fortunately we can fix it for dnx: Bridge.Builder.dll should have [Program](https://github.com/aspnet/dnx/blob/32358ec9b8970070ff77cbc5beef28c13e3ab09b/src/Microsoft.Framework.Runtime.Sources/Impl/EntryPointExecutor.cs#L86) class with static Main function

hope this helps

**Comment by antonmes** [comment]
The class in Bridge.Builder is already named correctly, i guess it's the ilmerge issue. I build Brige.Builder as library without merging and it works with dnx.

```
$ dnx ~/.dnx/packages/Bridge/**/tools/Bridge.Builder.dll -lib build/Demo.dll
Generating script...
Saving to .../Demo/Bridge/output
Extracting core scripts...
Done.
```

**Comment by fabriciomurta** [comment]
The thing is that Bridge.Builder.exe is the commandline build tool, which we are using, and it is the same (essentially) as Bridge.Builder.dll (which is a merge of several dependency DLLs into one).
The difference is that Bridge.Builder.dll (or Bridge.Build.dll when not packed with ILMerge) is meant to be run in a UsingTask when we are talking about Visual Studio.

Additionally, the NuGet packages have only the Bridge.Builder.dll (bundled with ILMerge), and not Bridge.Builder.exe.

The way Bridge.Builder.dll is called is as follows:
```
<UsingTask TaskName="GenerateScript" AssemblyFile="$(MSBuildThisFileDirectory)..\tools\Bridge.Builder.dll" />

  <Target Name="AfterBuild">
    <GenerateScript
      OutputPath="$(OutputPath)"
      Configuration="$(Configuration)"
      Assembly="@(IntermediateAssembly)"
      AssembliesPath="$(OutputPath)"
      ProjectPath="$(MSBuildProjectFullPath)">
    </GenerateScript>
  </Target>
```

So, there must be a way to run the equivalent with DNX or mono. I have researched a bit and I see that if I am using the .csproj syntax with mono I should make it. But I was interested in keeping your approach of using just 'project.json' instead of depending of Visual Studio on Windows to generate the files.

The demo works right now because it still haves a Bridge.Builder.exe committed in that's compatible with that we pull from NuGet. But this can't be guaranteed for the medium term.

**Comment by fabriciomurta** [comment]
Oh, I seem to have lost a little the main purpose of this thread. We got Intellisense working once changed the NuGet package from `Bridge.NET` to just `Bridge`. Right? If you don't feel like it is appropriate to close the thread now, please let us know.

We're dealing with Bridge.Builder.dll in bridgedotnet/Builder#16.
