### ISSUE TITLE
Error sharing code on Deck.net

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2557]
Not sure if there's a better place to raise this, but couldn't find a deck repo. When clicking Share on Deck using the code below, the URL text box remains blank and you get an error in the console:

> Refused to execute script from 'https://api.github.com/gists?{%20%22description%22:%20%22deck.net%22,%20%20…0Activator.CreateInstance(typeof(T));\n}\n}%22%20%20}%20}}&_=1491834821272' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

Seems to be particular to this code; trimming it down seems to fix the issue.

```cs
public static class EnumExtensions
{
public static T GetAttribute<T>(this Enum value)
where T : Attribute
{
var customAttribute = value
.GetType()
.GetField(value.ToString())
.GetCustomAttributes(typeof(T), false) 
.FirstOrDefault()
as T;

return customAttribute ?? (T) Activator.CreateInstance(typeof(T));
}
}
```

**Comment by geoffreymcgill** [comment]
Hi @DanTup – Thanks for the report. This Deck.NET bug has something to do with the C# code containing `??`.

I've recreated the issue at deckdotnet/Deck.NET/#17.

**Comment by DanTup** [comment]
Ah, I didn't test with that, I was expecting it to be the chevrons or something! Thanks!

**Comment by geoffreymcgill** [comment]
Hi @DanTup – The defect has been fixed and https://dev.deck.net has been updated. This fix will be pushed to https://deck.net once Bridge 16.0 is ready.

Looks like the source of the problem is a defect(?) in jQuery. Here's a few references to the problem we found:

* https://stackoverflow.com/questions/17532018/submitting-jquery-ajax-data-with-string-containing-it-changes-value-to-jq
* http://stackoverflow.com/questions/5707619/uncomprehensible-jquery-ajax-behavior-when-data-contains-consecutive-questio
* https://forum.jquery.com/topic/strange-string-at-the-end-of-my-mesages-jquery15012356981023933311-1302979842877

We were also able to reduce the sample down to the following:

https://dev.deck.net/330999808d634cfd4638c214b0f8f57b

```csharp
public class Program
{
    public static void Main()
    {
        // ??
    }
}
```

Thanks again for reporting the defect.

**Comment by DanTup** [comment]
Amazing. I'm already not a fan of jQuery and magic behaviour like this only makes things worse! 😖
