### ISSUE TITLE
RequireJS and AMD support

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#258]
Bridge forum thread: 
http://forums.bridge.net/forum/general/feature-requests/217

**Comment by DaniilVeriga** [comment]
As of version 1.7.0, the `[Module]` and `[ModuleDependency]` might be used to organize modules. There are mode details in [this forum post](http://forums.bridge.net/forum/general/feature-requests/217?p=361#post361).

**Comment by kasperp** [comment]
Are there any news on CommonJs support ?

**Comment by DaniilVeriga** [comment]
Hi @kasperp,

Thank you for your interests, but, unfortunately, I don't have good news - CommonJS support is still not implemented and we don't have a solid time frame for that. 

Meanwhile, decided to split the current issue into two. The current issue is left for AMD and RequireJS support and being closed, because it was implemented. For CommonJS support an individual issue has been created - #813.

**Comment by kasperp** [comment]
@DaniilVeriga thanks for getting back. 

Would es6 module support also go #813 or would you prefer a separate issue for that ?

**Comment by DaniilVeriga** [comment]
I tend to think that an individual issue with cross-references is the best option.

**Comment by danfma** [comment]
I'm playing with the module support and I saw that it does not support path based modules. For example, when using [Module("path/to/my/module")].

This is important if you want to generate path related modules, like for simulating dynamic loading with frameworks like aurelia and angular 2 or even to work with some route libraries.

**Comment by geoffreymcgill** [comment]
Module support has been completely redesigned and will be available in the next release of Bridge. See Issue #2217.
