### ISSUE TITLE
Make an official awesome-bridge repo?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [bridgedotnet/Bridge#2726]
Just like other awesome-* repos, a place to put team and community efforts (links to libraries, blogs, bindings, demos etc.) in one place that easily searchable for other people. At this point, Bridge needs one :smile:.

**Comment by hardhub** [comment]
@Zaid-Ajaj 

Do you mean this?

https://github.com/bridgedotnet/Frameworks

All packages available from nuget.

**Comment by Zaid-Ajaj** [comment]
@hardhub an awesome-* repo is not a code repo, but rather a place with links to many other places: repos, articles, blogs, talks, video tutorials, tools, and other stuff, this is for example what [awesome-dotnet](https://github.com/quozd/awesome-dotnet) looks like

**Comment by hardhub** [comment]
OK

Blog is available at bridge.net, forums there, faq. Maybe libs and 3rd parties also can be described in Resources section.

Should it be github based repository? I am not sure..  So it is for brdige team decision.

**Comment by geoffreymcgill** [comment]
Hi @Zaid-Ajaj – Thanks for the great suggestion. We will discuss this today.

**Comment by geoffreymcgill** [comment]
Done.
https://github.com/bridgedotnet/Awesome

**Comment by kcudnik** [comment]
You could update copyright info in license file :)

**Comment by geoffreymcgill** [comment]
> You could update copyright info in license file :)

Done.

**Comment by geoffreymcgill** [comment]
@Zaid-Ajaj – Thanks for publishing the awesome article on using **Bridge.React**!!

https://medium.com/@zaid.naom/building-react-applications-in-c-a-beginners-guide-5a2d001744c4

@ProductiveRage, did you see?

**Comment by ProductiveRage** [comment]
Yes I did - @Zaid-Ajaj, great work! Managed to cover a lot of material in a relatively short article (which is something that I struggle with, mine are often very long) that was easy to absorb :)

**Comment by Zaid-Ajaj** [comment]
@geoffreymcgill, @ProductiveRage  Thanks for the kind words, I am glad you liked it :smile:

**Comment by ProductiveRage** [comment]
@Zaid-Ajaj - the only thing that I was going to say was that there is a workaround for your comment:

Pro Tip: When adding a class to your project with “Add New Item”, do not add a class but rather an empty code file. If you add a class, it will automatically reference the original mscorlib to the project which makes Bridge unhappy

See https://forums.bridge.net/forum/community/help/3891-system-assembly-keeps-getting-added-to-the-vs-2015-bridge-net-project

I must admit that I haven't actually tried it yet (I do a similar workaround to you except that I tend to copy-paste existing files, which seems to bypass the reference "fixing") but I keep meaning to try this approach out.

I'm not sure if this is going to become something that is done automatically when the Bridge NuGet package is installed (since it has to perform other manipulations on the project file, it might make sense to do this too); @geoffreymcgill ?
