### ISSUE TITLE
Enum property of "name" does not convert correctly to JavaScript

### ISSUE THREAD

**Issue by FasettoAndrew** [bridgedotnet/Bridge#2961]
When converting a enumerator to JavaScript, naming a value of the enum as "Name" or "name" causes the JavaScript to be incorrectly evaluted to "$name".

### Steps To Reproduce

https://deck.net/51cceb8b543b043a5f2602dec3b29115

```c#
public enum OtherEnum
{
    One = 1,
    Two = 2,
    ContentName = 3,
    name = 4,
    Name = 5
}
```

### Expected Result

```js
    Bridge.define("OtherEnum", {
        $kind: "enum",
        statics: {
            fields: {
                One: 1,
                Two: 2,
                ContentName: 3,
                $name: 4,
                Name: 5
            }
        }
    });
```

### Actual Result

```js
    Bridge.define("OtherEnum", {
        $kind: "enum",
        statics: {
            fields: {
                One: 1,
                Two: 2,
                ContentName: 3,
                $name: 4,
                $Name: 5
            }
        }
    });
```

**Comment by michaelcheers** [comment]
### See also

* #2955

**Comment by vladsch** [comment]
Static member name cannot have 'name' as naming. The scope of a static member is a class (class is a function in javascript). In javascript, each function has some predefined properties which we cannot replace by own. 'name' is one of them.
That's why Bridge add $ prefix to such name. The single change which we should change that only lower case `name` should be prefixed.
