### ISSUE TITLE
Error using custom Element with Generics

### ISSUE THREAD

**Issue by alan-azvd** [bridgedotnet/Bridge#2995]
I'm creating custom tags that do not yet exist in the bridge.html5 namespace like nav aside i.
I have that:

```c#
[External]
[Name("HTMLNavElement")]
public sealed class HTMLNavElement : HTMLElement<HTMLNavElement>
{
    [Template("document.createElement('nav')")]
    public HTMLNavElement() { }
}
````

Then if I want to use a generic class that uses this class:

```c#
public class ClassA<T> where T : HTMLElement
{

}

public class ClassB : ClassA<HTMLNavElement>
{

}
````

I get a browser error:

"Uncaught ReferenceError: HTMLNavElement is not defined".

If I use
```c#
public class ClassB : ClassA<HTMLDivElement>
{

}
```
Everything works correctly.

**Comment by geoffreymcgill** [comment]
You are getting this error because **HTMLNavElement** is defined as `[External]` so Bridge is expecting the definition of this class to be provided elsewhere (not controlled by Bridge).

The **HTMLNavElement** class does not exist during runtime. Your `ClassA<HTMLDivElement>` sample works because **HTMLDivElement** does exist during runtime.

## See Also

* Support for Custom Elements #2580

**Comment by alan-azvd** [comment]
The implementation of HTMLDivElement is the same as I did in HTMLNavElement
[https://github.com/bridgedotnet/Bridge/blob/master/Html5/Elements/HTMLDivElement.cs](url)

**Comment by geoffreymcgill** [comment]
> The implementation of HTMLDivElement is the same as I did in HTMLNavElement

Yes, but **HTMLDivElement** exists on the client, and **HTMLNavElement** does not.

**Comment by alan-azvd** [comment]
ok, I got it!
Thanks!

**Comment by AndreyChechel** [comment]
The issue in the initial sample could be solved by applying `[Virtual]` attribute instead of `[External]` (see more details [here](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#virtual)).
