### ISSUE TITLE
DateTime.ToString with "g" format different for "en-US" locale

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3048]
Just check the output of the sample code. 
Only "g" format is tested (in theory others also can be wrong).

### Steps To Reproduce

https://deck.net/ac08fe8b3258d9b7ccfad30eaabe8431
https://dev.deck.net/ea23ea1137ed895865145606862fa932
https://dotnetfiddle.net/gwVQWH

Result on DotNetFiddle, Windows (.Net Framework) and under Linux (Mono) is the same.

```c#
using System;
using System.Globalization;
					
public class Program
{
	public static void Main()
	{
                CultureInfo culture = CultureInfo.GetCultureInfo("en-US");

                Console.WriteLine(DateTime.Now.ToString("g", culture));
	}
}
```

### Expected Output

```
8/13/2017 12:40 PM
```

### Actual Output

```
08/13/2017 15:40
```

**Comment by geoffreymcgill** [comment]
Thanks for reporting this issue. Several default DateTime formats were not correct and have been updated. 

This fix will be included in the next release of Bridge.

**Comment by geoffreymcgill** [comment]
In Bridge, by default, the locale files are not automatically loaded. 

You can add the following configuration to your projects **bridge.json** file to automatically include the specified locale .js file.

```json
"locales": "en-US"
```

More info at:
https://github.com/bridgedotnet/Bridge/wiki/global-configuration#locales

Hope this helps.

**Comment by geoffreymcgill** [comment]
I configured Deck.NET to include the `en-US` locale file by default. Your original Deck now works correctly:

https://deck.net/ea23ea1137ed895865145606862fa932

We're going to have to figure out a way to automatically load the locale files automatically when the Culture is specified. For now, setting the `locales ` config in **bridge.json** is required.

**Comment by hardhub** [comment]
I see...

Just one question...
Should CultureInfo.CurrentCulture be Invariant Culture (iv) by default even if all required locales are added to json config?

https://deck.net/0a1251b0d326c9ae7b35cd379bdd9ddb

**Comment by geoffreymcgill** [comment]
The `locales` config will load the .js files, although the CurrentCulture still must be set in your App.

I believe in .NET by default, the CurrentCulture is set to the Language of the current App thread. 

If the app is running in a browser, the CurrentCulture could be mapped to the browsers `navigator.language` setting.

https://deck.net/bb5846ae79bc272ec465ef194ce8e58f

```csharp
public class Program
{
    public static void Main()
    { 
        Console.WriteLine(Global.Navigator.Language);
    }
}
```

**Comment by geoffreymcgill** [comment]
I guess the question for me is, should Bridge be attempting to automatically map the browsers `navigator.language` value to the CurrentCulture value and load the appropriate locale file?

This would most closely match the native .NET functionality, but would almost certainly produce unexpected results with end users of the app.

So default options could include:

1. Use InvariantCulture (current functionality) and require the explicit setting of the CurrentCulture to override. 
2. Try to determine Culture from the browser at runtime and load appropriate locale file. Fall back to InvariantCulture (or `en-US`?) if the runtime Culture cannot be determined.
3. Use `en-US`.
4. New `culture` config in **bridge.json** to set the default Culture. Maybe the `locales` settings could be merged into `culture`.

Personally, I like option 4 best. 

What Culture would option 4 default to? Maybe we could determine the CurrentCulture at compile time and just use that instead of trying to determine at runtime.

**Comment by hardhub** [comment]
In my personal opinion 2 is better than others.
Imagine you have some console app running in some environment...
If that system has corresponding locale then app uses it by default (no config of console app is required).
It makes sense if you want to make Bridge closer to .Net runtime.

So if environment have such ability to provide culture then it should provide.
I think all available locales should be specified in config (like it is now).
And browser will "select" default locale based on "what it wants and what he has".

In comparison to many jquery controls (where 'en' is some sort of invariant locale) en-US culture in Bridge is separate culture...  so fallback as InvariantCulture is really good idea... 
My suggestion just to ask browser (any other environment) and use such locale if available.
