### ISSUE TITLE
Inconsistencies in IDictionary, ICollection, IList, etc

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3223]
All of these interfaces have methods that do not exist in .NET Framework's equivalent interfaces and have other missing methods. I also noticed that some other interfaces like `IOrderedDictionary` are missing.

**Comment by TriEdgeAI** [comment]
Any ETA for this?

**Comment by DierkDroth** [comment]
In particular I found that
- .[Clear](https://docs.microsoft.com/en-us/previous-versions/windows/apps/ac8h88b7(v=vs.105)?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Collections.IDictionary.Clear)%3Bk(DevLang-csharp)%26rd%3Dtrue)
- .[Contains](https://docs.microsoft.com/en-us/previous-versions/windows/apps/9f2wxt1w(v=vs.105)?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Collections.IDictionary.Contains)%3Bk(DevLang-csharp)%26rd%3Dtrue)
... are missing in IDictionary which is getting into our way.

Would those be covered by that issue as well?

**Comment by TriEdgeAI** [comment]
pls premium

**Comment by geoffreymcgill** [comment]
The team will be able to work on this issue after the 16.7.0 release, which is scheduled for 2018-01-22. 

We will plan for these changes to be included in the 16.8.0 milestone.

**Comment by DierkDroth** [comment]
Thanks for the update @geoffreymcgill

**Comment by fabriciomurta** [comment]
Reviewing both [System.Collections.IDictionary](http://referencesource.microsoft.com/#mscorlib/system/collections/idictionary.cs,ea6b36745fa51e08) and [System.Collections.Generic.IDictionary](http://referencesource.microsoft.com/#mscorlib/system/collections/generic/idictionary.cs,20343df0c96b629b) I couldn't find a reference to `Clear()`. But `Contains()` is there (in System.Collections.IDictionary).

So well, unless we clarify in which interface you are missing the `Clear()`, we can't just add it to any of those.

Basically what I could find was just:
- System.Collections.ICollection: Missing SyncRoot and IsSynchronized
- System.Collections.IDictionary: Mismatching inheritances/interface references, extra 'Remove()` method and `ContainsKey()` instead of `Contains()` implementation
- System.Collections.IDictionaryEnumerator: Completely missing
- System.Collections.DictionaryEntry: Completely missing
- System.Collections.IList: Missing IsFixedSize

System.Collections.Generic.* interfaces looked good as far as I could find.

Do you want to take a look before we assume this issue is done? I don't have more good clues on following the "etc" part of the issue. :) If so, the current implementation is available at branch Issue3223, backed by pull request #3411.

**Comment by DierkDroth** [comment]
Hmm ... I see this in the IDictionary link you provided

// Removes all pairs from the dictionary.
        void Clear();

Is that what you're looking for?

**Comment by fabriciomurta** [comment]
Gee you're right! I've looked that not once but only saw it in the CONTRACTS_FULL section. Might have typed something wrong! Who knows!

**Comment by fabriciomurta** [comment]
That was an easy addition, it seems all implementations referencing `System.Collections.IDictionary` already had `Clear()` defined. If some missing, we should treat in a case-by-case now. So to the list above:
- System.Collections.IDictionary: Added `Clear()` method to the interface contract.

With this, at least the list you provided is fullfiled. Hopefully the original list is now good too. If okay, we'll be merging the pull request.

**Comment by TriEdgeAI** [comment]
Looks good :)

**Comment by fabriciomurta** [comment]
The changes have just been merged upstream and will make it to the next Bridge release (see attached milestone).

**Comment by DierkDroth** [comment]
Great, thx
