### ISSUE TITLE
New ObjectLiteralRule

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3257]
Proposal to add a new **[ObjectLiteralRule](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#rules)** to determine if Type information should be included with classes marked with the `[ObjectLiteral]` attribute. 

Name | Options | Description
---- | ---- | ----
objectLiteral | "Managed" or "Plain" | Set to "Plain" to exclude Type information. Default is "Managed".

This proposal would also require, by default, adding Type information to the generated metadata when `[ObjectLiteral]` is used. Currently, no Type information is added to the metadata unless `[ObjectLiteral(ObjectCreateMode.Constructor)]` is applied.

If `"objectLiteral": "Plain"` (proposed default functionality), the following sample with a **DateTime** object would have enough type information to deserialized correctly. Currently, fails unless `[ObjectLiteral(ObjectCreateMode.Constructor)]`.

https://deck.net/e9b94490409ad48e416084311e38a60e

```csharp
public class Program
{
    public static void Main()
    {
        Product product = new Product();
        product.ExpiryDate = new DateTime(2008, 12, 28);

        string output = JsonConvert.SerializeObject(product);

        Product deserializedProduct = JsonConvert.DeserializeObject<Product>(output);
        Console.WriteLine(deserializedProduct.ExpiryDate);
    }
}

[ObjectLiteral]
public class Product
{
    public DateTime ExpiryDate { get; set; }
}
```

**Comment by ProductiveRage** [comment]
I think that there may be two different use cases and I want to ensure if you're trying to address one or both (or neither!) of them..

The first case is for when I have an instance "x" of [ObjectLiteral] class "MyClass" and I want to interrogate its meta data - for example, I want to know what properties are available on instance "x".

The second case is for when I know that I want to deserialise an instance of "MyClass" and I want to interrogate the meta data of that class to know what properties are available.

I would imagine that the first case would require additional Bridge-specific fields being added to the ObjectLiteral representation (such as a $type or $getType value)? This could potentially cause problems for people using [ObjectLiteral] to generate types to communicate with external JS code? But I guess that's why you'll be making this a configurable option!

It's the second case that I'm really interested in, though. When I'm deserialising, I know that I want to deserialise to type "Product" and so it's important that the properties of the Product class be retrievable so that DateTime values (for example) can be deserialised correctly. If this was a deeper object graph than just a single Product that I wanted to deserialise then it would be important to be able to get the types of other properties because one property may be of a different [ObjectLiteral] type that also has a DateTime field that must be correctly parsed. For this use case, I not have thought that any additional properties would need to be injected into the representation of the [ObjectLiteral] class at runtime, it would only need to generate some additional metadata so that when I call typeof(Product).GetProperties() that the properties data comes back?

I've read the initial proposal here several times but I'm not completely sure which of these use cases (if not both) that you are tackling. If the serialisation example you've shown will work with the new setting then surely the second case is covered - I'm just trying to get my head around any possible ramifications of doing so (and by this behaviour being the default)!

**Comment by geoffreymcgill** [comment]
Thanks for the excellent feedback. Can you demonstrate both scenarios in code by sharing a Deck? That way we're all on the same page.

**Comment by ProductiveRage** [comment]
Here's some code that hopefully demonstrates what I'm talking about:

```
public class Program
{
    public static void Main()
    {
        // This isn't either use case 1 or 2, it's just what I imagine the most common
        // [ObjectLiteral] usage to be: I want to pass an object to some external JavaScript
        // library and I want that object to have zero Bridge.NET annotations - just a clean,
        // simple object
        var config = new MyLibraryConfig { Id = 123 };
        PretendExternalJavaScriptMethod(config);
        
        // This is use case 1: I have an instance of something and I want to use reflection
        // to look at its properties.. for some reason. Personally, I am not particularly
        // interested in this case.
        var properties = config.GetType().GetProperties();
        if (properties.Any())
        {
	        foreach (var property in properties)
    	        Console.WriteLine("config has property " + property.Name);
        }
        else
            Console.WriteLine("config has no properties");

        // This is use case 2: I want to deserialise some JSON to a known [ObjectLiteral]
        // and I want to be confident that it will deserialise correctly. I imagine that,
        // order for this to work, "typeof(MyLibraryConfig).GetProperties()" will return
        // the properties on the class, even though "config.GetType().GetProperties()"
        // above returned zero results (because there is no way for the runtime to know
        // that the object literal is of type "MyLibraryConfig" unless additional values
        // are injected into it, such as $type or $gettype values - but we don't want them
        // if we're using [ObjectLiteral] to get free-from-Bridge-annotations objects).
        var json = "{\"Id\":456}";
        Console.WriteLine(json);
        var deserialised = JsonConvert.DeserializeObject<MyLibraryConfig>(json);
    }
    
    private static void PretendExternalJavaScriptMethod(object config)
    {
        /*@
        // Parse config options
        var id = -1;
        for (var propertyName in config) {
        	switch (propertyName) {
        		default:
                	throw new Error("Unrecognised config value: " + propertyName);
                case "Id":
                	id = config[propertyName];
            }
        }
        */
    }
}

[ObjectLiteral]
public class MyLibraryConfig
{
    public int Id { get; set; }
}
```

(Available at [deck.net/b8ae33d45647d58a8fb79f700d452a09](https://deck.net/b8ae33d45647d58a8fb79f700d452a09)).

It's quite possible that my assumption that [ObjectLiteral] is mostly used when "I want to pass an object to some external JavaScript library and I want that object to have zero Bridge.NET annotations" is not something that you agree with.

**Comment by geoffreymcgill** [comment]
We can review this proposal again in the future, but for now, it doesn't make much sense.

**Comment by emumanu** [comment]
Hello,

I found myself in this scenario:

I want to pass an object to some external JavaScript library and I want that clean object to pass.

However, I also want to create "bridge managed objects" that rely on the metadata for type marked as ObjectLiteral.

For example. I have this class:

```cs
[ObjectLiteral]
public class RatingInfo
{
    public float value;
}
```
To fire an event I do this:

```cs
this.fireEvent<RatingInfo>("change", new RatingInfo {
    value = this.getProperty<float>("value")
});
```
However, to define the events I need to do something like:

```cs
new UI5EventInfo() {
    parameters = new Dictionary<string, UI5ParameterInfo>() {
        { "value", new UI5ParameterInfo() { type = "float" }}
    }
}
```
And with the metadata, I just can do:

```cs
TypedMetadata.CreateUI5EventInfo<RatingInfo>()
```
having this code:

```cs
public static partial class TypedMetadata
{
    public static UI5EventInfo CreateUI5EventInfo<T>()
    {
        var paramDict = new Dictionary<string, UI5ParameterInfo>();

        // copies non static fields
        foreach (FieldInfo field in typeof(T).GetFields().Where(f => !f.IsStatic)) {
            paramDict[field.ScriptName] = new UI5ParameterInfo() {
                type = GetUI5Type(field.FieldType)
            };
        };

        UI5EventInfo evt = new UI5EventInfo() {
            parameters = paramDict
        };

        return evt;
    }
}
```

I'm using a workaround that consits in using a class not marked with [ObjectLiteral] but marked as [Constructor("{}")], but it feels ugly and dirty, as the semantic meaning given by the ObjectLiteralAttribute is lost. 
Please add the option to object literal to support this scenario. Thank you!

**Comment by AndreyChechel** [comment]
@emumanu, do you think `Bridge.Script.ToPlainObject()` can be helpful for your scenario?

https://deck.net/33a8776596073c4eb2f1bc9c8335920d

```cs
public class Program
{
    public static void Main()
    {
        var person = new Person 
        {
            FirstName = "John",
            LastName = "Smith"
        };
        
        var plainPerson = Script.ToPlainObject(person);
        
        //@ console.log(person);
        //@ console.log(plainPerson);
    }
}

class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

**Comment by emumanu** [comment]
@AndreyChechel,

I don't think so. 

I'm in case 1 described by @ProductiveRage and the example I posted above works perfectly if I define RaingInfo like:

```cs
[Constructor("{}")]
public class RatingInfo
{
    public float value;
}
```
and semantically, it feels very natural (it is a strongly typed version with some candy compared to using the javascript library directly) and straightforward except for the missing [ObjectLiteral] in the top of RatingInfo.

I can live with that but I think that something like [ObjectLiteral(TypeInformation.Managed)] would be nicer and more cohesive.
