### ISSUE TITLE
Missing Type.IsValueType

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3282]

**Comment by fabriciomurta** [comment]
[System.Type.IsValueType](https://docs.microsoft.com/en-us/dotnet/api/system.type.isvaluetype?view=netframework-4.5#System_Type_IsValueType)

Hello, and thanks for reporting this! I'm not sure why this is not implemented, maybe just not implemented due to choosing other stuff to implement at all. But now we got this, thank you!

**Comment by vladsch** [comment]
Implemented in #3329
