### ISSUE TITLE
Can no longer raise bug reports on forums.bridge.net?

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge#3326]
If I go here:

https://forums.bridge.net/forum/bridge-net-pro/bugs

then there doesn't appear to be any "New Post" button. Is that a change or a mistake?

I realised that if I start here

https://forums.bridge.net/forum

and go to Premium Help (https://forums.bridge.net/forum/premium/premium-help) that maybe there would be no New Post button since I'm not a Premium member yet but it seems like I can't raise reports at all on the forum site!

Hardly the end of the world since I can raise GH issues but I thought that it was worth mentioning.

**Comment by fabriciomurta** [comment]
Hello @ProductiveRage! Sorry for the problem. The "bugs" forum is now inside the "premium" section of the site. So if you are not premium, you should not be able to post there.

But don't worry, post your bug report within the [community *Help forum](https://forums.bridge.net/forum/community/help), then we move the report to the bugs forums as soon as it gets confirmed as a bug by us.

In fact, even premium users will not be able to post in the *Bugs* forums directly. Instead, the reports/requests can be made in the [Premium Help](https://forums.bridge.net/forum/premium/premium-help) forum. Likewise, when we confirm the thread as a bug, we just move them within the bugs forum.

**Comment by geoffreymcgill** [comment]
I removed @fabriciomurta response since it contained some wrong information. 

The [Bugs forum](https://forums.bridge.net/forum/bridge-net-pro/bugs) will be open for everyone to post. Looks like it picked up the Premium group permissions when it was moved. All members should have access to create threads now. Please let me know if you do not.

Even through the **Bugs** forum is in the **Premium** forum group, the permissions are set to allow all members to create new threads, and to participate in any thread. The Bugs forum was placed inside the Premium group mainly out of convenience. I wanted it high on the forum page, it doesn't fit only in the Community group, I didn't want to create two bugs forums, etc. With the correct permissions, it seemed to fit best in the Premium group. 

We are going to encourage all Bug reports to be reported in the [forums](https://forums.bridge.net/forum/bridge-net-pro/bugs) vs GitHub. The Bridge team will move verified bugs or feature requests from the forums into [GitHub issues](https://github.com/bridgedotnet/Bridge/issues/) as required.

Hope this helps clarify the process.
