### ISSUE TITLE
Passing an instance of a custom implementation of IComparer<T> to List<T>.Sort() does not work

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3394]
https://deck.net/34af09d7ae20c20d3c4f7c66a5bd6905

**Comment by AndreyChechel** [comment]
The reason of the issue is that the `Compare` method gets a different name when used as explicit implementation for `IComparer<T>` method. That name is constructed according naming rules for interface members.
```js
methods: {
   System$Collections$Generic$IComparer$1$System$Int32$compare: function (a, b) {
      return Bridge.compare(a, b);
   }
}
```

However, `sort` function relies on the exact function name of the provided comparer, which is `compare`.
```js
array.sort(Bridge.fn.bind(comparer, comparer.compare));
```

The possible fix is to check both methods, `compare` and the one from `ICompare<T>` interface: `System$Collections$Generic$IComparer$1$compare`. So the implementation will look like:
```js
var compareFn = comparer.compare ||
                comparer["System$Collections$Generic$IComparer$1$compare"];

if (index === 0 && length === array.length) {
    array.sort(Bridge.fn.bind(comparer, compareFn));
} else {
    var newarray = array.slice(index, index + length);
    newarray.sort(Bridge.fn.bind(comparer, compareFn));

    // ...
}
```

**Comment by TriEdgeAI** [comment]
Thank you very much for the quick help!
I implemented it like so:

```js
var compareFn = comparer.compare ||
                comparer["System$Collections$IComparer$compare"] ||
                comparer["System$Collections$Generic$IComparer$1$compare"];
```

**Comment by fabriciomurta** [comment]
Fixed! Will make it to next Bridge release (see milestone).
Looks good in deck now (no exception at least): https://dev.deck.net/34af09d7ae20c20d3c4f7c66a5bd6905

**Comment by TriEdgeAI** [comment]
Thanks so much!
