### ISSUE TITLE
Exception during construction of jqXHR

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3493]
It can be compiled in both cases. But second one raises exception in console.

### Steps To Reproduce

https://deck.net/88636364d1821522e498aba41cbbefbe

```csharp
jqXHR xhr1 = null; // Works
jqXHR xhr2 = new jqXHR(); // Does not work!
```

### Expected Result

```
No exception and constructed object with "jQuery.ajaxSettings.xhr();"
```

### Actual Result

```
Exception, jQuery2 is not defined.
```

**Comment by geoffreymcgill** [comment]
Looks like **jqXHR** class should be marked as `abstract`. You shouldn't be able to _new up_ an instance of **jqXHR**. 

We would also recommend using [Retyped.jquery](https://www.nuget.org/packages/retyped.jquery) package instead of Bridge.jQuery.

Here's a basic jQuery AJAX sample using Retyped.jquery:

https://deck.net/webservice

We're providing only very limited support for the **Bridge.jQuery** package, but if you want to send a PR to change to `abstract`, please submit the PR to the [Frameworks](https://github.com/bridgedotnet/Frameworks) repo.

**Comment by hardhub** [comment]
> We would also recommend using Retyped.jquery package instead of Bridge.jQuery.

Jeff I tried to switch to Retyped and it was not successful. It is not worth anything.

It does not allow to use some things actual for my code.. Just small example:

```
public static byte[] Deflate(this ArrayBuffer binary)
{
     return Pako.Deflate(new Uint8Array(binary)).ToArray();
}
```

Uint8Array  wants ArrayBufferLike and not ArrayBuffer.  
There is no way to convert ArrayBuffer to ArrayBufferLike.  
And it requires much more complex and verbose code.  

> if you want to send a PR to change to abstract

No I want to add support of jQuery.ajaxSettings.xhr();

> please submit the PR to the Frameworks repo.

It does not make any sense. I created this issue https://github.com/bridgedotnet/Frameworks/issues/70 more than 6 months ago and nobody replied since that moment.

**I do not think it can be named "premium" support.**
