### ISSUE TITLE
Guid.ToString seems unneccessarily performance-inefficient

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3709]
Not a very important issue, but reporting it and you guys can choose what to do with it.

Been tracking the performance of my application lately to improve experience on lower-end pads/cellphones, and seems one of the major single points of slowdowns is caused by Guid.ToString. My application calls it not really more times than neccessary, just once each time a new Guid is generated in a loop with 30-40 items.

Looking at the calltree caused by Guid.ToString it seems there is significantly room for improvement / complexity reduction. A single call to Guid.ToString seems to:
- Visit 67 distinct javascript functions
- Construct a significant number of temporary items for immediate garbage disposal

See attached calltree.

![guid tostring](https://user-images.githubusercontent.com/38761430/45263423-74bcf700-b429-11e8-99a1-3122974f7526.png)

**Comment by fabriciomurta** [comment]
Thanks for the performance bottleneck pointing! Sometimes to keep code more readable we may not make the best judgement given the frequency or loophole the function may do, and having someone point it so that we can review in the future really helps. At the least, we know that people use it and that it affected negatively a real world application.

If this annoys you and you just know what to do to improve it, remember you can always post pull requests to Bridge. They are really welcome!

**Comment by fabriciomurta** [comment]
This is how it looks after the fix @vladsch applied (suggestion: open the animation in a new window)...
![3709-difference](https://user-images.githubusercontent.com/10730372/46450553-31c01c00-c768-11e8-806a-407c258ab8e0.gif)

**Comment by ChrML** [comment]
Wow, that is a really significant improvement. Great job!

**Comment by fabriciomurta** [comment]
If you look at the related pull request, there's a deck code with a test case and the expected improvement in performance. You may try it today with `deck.net` and then `dev.deck.net` to see the difference.

That said, the optimization has been implemented and will make it to the next Bridge release (see milestone).
