### ISSUE TITLE
Enum.ToObject is missing

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3720]
The ToObject(Type, Object) method converts the integral value value to an enumeration member whose underlying value is value.

This conversion method returns a value of type Object: [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.enum.toobject?view=netframework-4.7.2#System_Enum_ToObject_System_Type_System_Object_)

Used [this](https://deck.net/fca682377389f97195846bde3944a980) as workaround.

**Comment by hardhub** [comment]
Got during tests:

```
C# to JavaScript Compilation Failed

System.IO.IOException: The process cannot access the file  
'E:\HostingSpaces\object\deck.net\wwwroot\Bridge\Builder\l4w0jq5c3opqrlq0dmdusbyn.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at Deck.Translator.BuildAssembly(String& path, String& error)
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
```

**Comment by fabriciomurta** [comment]
Hello, @hardhub! Thanks for reporting the issue (well, issue and missing feature).

It is good to know this issue is happening with Deck but as far as I've been trying here, not been able to reproduce it. If it starts getting to you very often (assuming you got this just once?), please open a dedicated issue. If consistently reproducing it in a given deck/scenario, please include all information. This might have been an occasional slowdown that culminated in the temporary DLL being stuck between two builds. At least we will keep an eye open for this happening again with Deck.

**Comment by hardhub** [comment]
> assuming you got this just once

Only once, when I executed multiple deck builds at the same time. Usually I do not need that :)  
So it is just FYI.. maybe to consider later (most likely related to thread-safety).

> include all information

Nothing else, that stack trace is only what I have.

**Comment by fabriciomurta** [comment]
Implemented! The method implementation will be available the Bridge release corresponding to this issue's milestone!
