### ISSUE TITLE
C# 7.1 default literal support

### ISSUE THREAD

**Issue by otabekgb** [bridgedotnet/Bridge#3726]
With latest version(17.3) vsix installed, I still get following exception on interface method signature

 public interface IAsyncEnumerable
    {
        Task<IAsyncEnumerator> GetAsyncEnumeratorAsync(CancellationToken cancellationToken = default);
    }

Error	CS8107	Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.	AsyncEnumerableBridge	D:\my-projects\bridgeDemo\AsyncEnumerableBridge\AsyncEnumerable.cs	117	Active

**Comment by fabriciomurta** [comment]
This also happens if you create a new, blank native Visual Studio Class Library project, so that's probably not within the reach or domain of the VSIX to define. To fix this you can just click the suggestions VS offers and choose to upgrade the project's C# language version.

![image](https://user-images.githubusercontent.com/10730372/46104123-f1c9c980-c1a8-11e8-9e36-c2b2270d552f.png)

If you know there is a way in VSIX to force this, let us know. I'm assuming the issue as invalid and closing it, but if you don't agree with that, also drop us a note.
