### ISSUE TITLE
Bridge.global does not contain type from Retyped (particularly, Retyped.electron) and breaks code

### ISSUE THREAD

**Issue by SirUppyPancakes** [bridgedotnet/Bridge#3736]
When calling a static, generic method and passing a type from `Retyped.electron` (particularly `Retyped.electron.Electron.BrowserWindow`), and using either `generic inference` or `using static` shorthand, a call to `Bridge.global.Electron.BrowserWindow` is generated, but `Bridge.global.Electron` does not exist.

See the forum post here for more information: https://forums.bridge.net/forum/community/help/5930-bridge-global-cannot-read-property-property-of-undefined

### Steps To Reproduce

1. Download and extract this minimal Bridge + Electron project: [Electron_Bridge_Example.zip](https://github.com/bridgedotnet/Bridge/files/2452748/Electron_Bridge_Example.zip)

2. Run `yarn install`
3. Run `yarn build`
4. Run `yarn start`
5. Note the error message that pops up and the console output that is printed.
6. Open `MainProcess.cs` and `bridge/MainProcess.js` and take a look at the bottom sections that generate the calls to `Bridge.global.Electron` and what causes them.

### Expected Result

Not sure if `Retyped.electron` is incorrectly failing to set `Bridge.global.Electron` somehow (or if that's how it even works), or if I am supposed to be doing something different, or if this is a compiler bug.

Note: At the top of the `MainProcess.cs` file in the example code, it doesn't matter if I use `using Electron = Retyped.electron.Electron;` or `using static Retyped.electron;`, which was a theory that @fabriciomurta had about the issue. If you comment one out over the other, rebuild, and re-run the sample, the result is the same. Even so, I would expect the Bridge compiler to handle any possible way I could use a `Retyped` library, regardless of my `using` statement preferences.

### Actual Result

As seen in the `MainProcess.cs` file (and corresponding `bridge/MainProcess.js` file) in the sample, Bridge only correctly generates the type as `Electron.BrowserWindow` when I don't use `generic inference` or `using static` shorthand. Or again, maybe this is normal behavior, and it is the `Retyped.electron` package that is failing to set `Bridge.global.Electron`.

Either way, hopefully we can get to the bottom of the behavior. Thanks for you time!

**Comment by fabriciomurta** [comment]
Hello @SirUppyPancakes, asked a hand from @AndreyChechel about this issue, and he just noticed it is no longer actual in the latest Bridge (17.4.0). Some issues we merged in the path from where you noticed this probably fixed the issue. So, can you give it a try now? 

For the time being, we're going close it. We'll also mark it as "invalid", as we are not really sure which commit/issue/pr fixed the bug. But if you see it is still actual, let us know how to reproduce the issue, we may have missed something.

Andrey also wrapped up a deck that explored the possibilities circa this issue, that highlights the issue was not really related to retyped packages, but from within Bridge. https://deck.net/c573f345024a1b1cf1331cb5b1608d4d

**Comment by SirUppyPancakes** [comment]
Looks fixed to me. Thanks!
