### ISSUE TITLE
Circular Reference to System.dll

### ISSUE THREAD

**Issue by fatbananas** [bridgedotnet/Bridge#3772]
I have an existing project that already references System.dll. Adding Bridge creates a cyclic reference.
Using net 4.2.7
I've tried building my own version of Bridge with the system.dll removed but not sure how to output the bridge.min, console and meta dlls?

**Comment by fabriciomurta** [comment]
Hello, Bridge requies using its own implementation of `mscorlib` (or `System.*` namespace, which is probably you are referring to as *system.dll*).
In order to build a same project with Bridge, you'd have to create a new, Bridge-specific project, then transplant the C# code to Bridge.

You can, for example, share code between projects by using the source file linking feature from Visual Studio. To add linked files, you choose the *add as link* option in the open dialog's dropdown on lower-right corner when adding an *existing item* in Visual Studio.

Sometimes you may need to change the original/link files to partial classes, so you can extend them in Bridge with specific attributes (when you need so). This won't affect the original/native application, and will also allow the native .NET version to have specific code not included in Bridge.

I hope this helps!

We're closing this as this is not really a bug nor a feature that could make it to Bridge. Paradigm-wise, this can't be made possible in the .NET world, linking selectively between two same imported namespaces. Let us know if you don't agree with that.
