### ISSUE TITLE
use strict Is Bug in many browsers

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3817]
hi to bridge.net team
last day i try to use duocode for make a project, that is not good compare to free bridge.net
but something interest me, that work even in my Symbian browser, this is big benefit for me
when i try test bridge in my Symbian mobile, that don't work because that don't know what is  use strict Mode
that browser is opera mini, and is best for html_5 in mobile
use strict mode may not important in compiled application, because that just control clean codes

i offer drop "use strict"; from bridge.js because every browsers can run it
thanks a lot.

**Comment by fabriciomurta** [comment]
Hello @miladsadeghi72!

Isn't Symbian discontinued since 2013? I believe it is just Symbian that won't catch up with current technology and that strict mode should be supported by any actual browsers.

We raised the matter about turning the strict mode optional in the past (issue #688) and in the end decided all code should get strict mode anyway; so that we ensure Bridge generated code is the best possible for the supported browsers' implementation.

Have you tried removing the 'use strict' line from the output bridge code manually to see whether it worked on symbian still? There still may be problems running on it.

Issues #672 and #688 could help you understand why we added `use strict` to Bridge.

**Comment by miladsadeghi72** [comment]
yes i use bridge.net in Symbian, that work fine
but without use strict, because if i don't remove that it's not possible 
my browser is opera mini for Symbian
i test it and no problem
well, i see issues, but better get design again, this is software developing, for example when my team get design about something, we review that to make better design
at last this is just a offer no more, so if you think it's ok , we haven't any problem
thanks for every did.

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

hi to bridge.net team
last day i try to use duocode for make a project, that is not good compare to free bridge.net
but something interest me, that work even in my Symbian browser, this is big benefit for me
when i try test bridge in my Symbian mobile, that don't work because that don't know what is  use strict Mode
that browser is opera mini, and is best for html_5 in mobile
use strict mode may not important in compiled application, because that just control clean codes

i offer drop "use strict"; from bridge.js because every browsers can run it
thanks a lot.
