### ISSUE TITLE
when 17.7.0 release?

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3822]
hi to bridge.net team
in fact we waiting for new release of bridge.net, because we are using this technology in real project
we even made new relational database for use in bridge.net
but because of many bugs in bridge.net we can't use relations in that database

we made new hybrid technology before we knows about bridge.net [Our Hybrid Technology in github]( https://github.com/miladsadeghi72/Monsajem_WebsiteService)

we must know when bridge.net 17.7.0 get release, is less than a week or not?
what can we do? use bridge.net for every devices and web site? or use our technology just for native?

our design is very important, so please just tell something

thanks a lot, Monsajem_Incs

**Comment by miladsadeghi72** [comment]
@geoffreymcgill can you help to make design ?

**Comment by geoffreymcgill** [comment]
You can following the progress of Bridge 17.7 by filtering issues tagged with the `17.7.0` milestone.

https://github.com/bridgedotnet/Bridge/issues?q=is%3Aopen+is%3Aissue+milestone%3A17.7.0

Hope this helps.

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

hi to bridge.net team
in fact we waiting for new release of bridge.net, because we are using this technology in real project
we even made new relational database for use in bridge.net
but because of many bugs in bridge.net we can't use relations in that database

we made new hybrid technology before we knows about bridge.net [Our Hybrid Technology in github]( https://github.com/miladsadeghi72/Monsajem_WebsiteService)

we must know when bridge.net 17.7.0 get release, is less than a week or not?
what can we do? use bridge.net for every devices and web site? or use our technology just for native?

our design is very important, so please just tell something

thanks a lot, Monsajem_Incs
