### ISSUE TITLE
Referencing a type in a second assembly does not find the type....

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3840]
Hi,

- VS PRO 15.9.6
- Bridge 17.6.0

A description of the issue.

### Steps To Reproduce

- I attach my solution
- Basically a type `TripItem` declared in its own assembly as described from https://github.com/bridgedotnet/Bridge/wiki/work-with-data cannot be found when the main entry point is called:

![image](https://user-images.githubusercontent.com/4738140/52990538-c1870e00-345c-11e9-84c1-e6ceac5197d6.png)

As soon as I open the index.html I get:

```
TripSearchEngine.cs:29 Uncaught TypeError: Cannot read property 'Dtos' of undefined
    at Function.Main (TripSearchEngine.cs:29)
    at bridge.js:3321
    at HTMLDocument.delayfn (bridge.js:595)
    at HTMLDocument.listenHandler (bridge.js:615)
```

If I move the declaration of `TripItem` above `TripSearchEngine` then it works. 

So what am I missing when I need to reference the separate assembly `TripSeekerSearch.Common` for the types it contains?

**Comment by vladsch** [comment]
Is that separate assembly `TripSeekerSearch.Common` Bridge assembly?

**Comment by natiki** [comment]
No it is not a Bridge assembly. It is going to contain common code that is going to be shared with other VS projects. It is "identical" to the DTO class library from https://github.com/bridgedotnet/Bridge/wiki/work-with-data#the-solution-structure

**Comment by fabriciomurta** [comment]
To reference code in Bridge you should also build it in Bridge. Otherwise it will never know how it should tread with the javascript output.

In order to benefit of code reusage in your Bridge and non-Bridge projects, you should use the source file linking feature from VS. You can add specifics to some classes if you define them as partial.

For example, if you want to add bridge-only attributes to classes and keep the "central" file intact (so the non-Bridge project sees no references to Bridge-only stuff), you can define it as **partial** and have the attributes go to another file physically in the Bridge project.

If you're wondering about the project-level file linking, I believe this Microsoft blog post is pretty accurrate: [Linked Files in Visual Studio Solutions](https://blogs.msdn.microsoft.com/jjameson/2009/04/02/linked-files-in-visual-studio-solutions/)

Hope this helps!

**Comment by natiki** [comment]
@fabriciomurta Thanks, I missed the source linking step. All works well when I implement as such.

I do however have a question about the partial class implementation approach. If I had the following in my CENTRAL (non bridge) assembly:

```c#
namespace Central
{
     public partial MyClass 
     {
          public string MyProperty {get; set;}
     }
}
```

and then in my BRIDGE assembly:

```c#
namespace Central
{
     public partial MyClass 
     {
     }
}
```
This still means I would have to get the BRIDGE assembly to have a reference to CENTRAL which is what we are trying to avoid. So how are you supposed to implement a partial class approach. Is there an example somewhere?

**Comment by fabriciomurta** [comment]
What I mean is, suppose you have the **Central** and then the **BridgeCentral** projects. And define the `Central.MyClass` in **Central\src\Central.cs**. Just like you pointed above, implementing the `MyProperty` property.

Then you'd add this **Central\src\Central.cs** to the project **BridgeCentral** as a link. So now you have the same source code built both in the **Central** and **BridgeCentral** assemblies when you build it.

Suppose you want a bridge-only property to the same `Central.MyClass` class. You'd then create a new physical file in the **BridgeCentral** project called, say **BridgeCentral\src\CentralExtensions.cs**, then you'd set it like

```csharp
namespace Central
{
    public partial MyClass
    {
        public string MyBridgeOnlyProperty {get; set;}
    }
}
```

Then you build both **Central** and **BridgeCentral** projects.

When you link a native .NET project against **Central**, you'd then have `Central.MyClass.MyProperty` available.
When you link a Bridge project against the bridge version of Central, **BridgeCentral**, you'd have the common `Central.MyClass.MyProperty` -and- the bridge-specific `Central.MyClass.MyBridgeOnlyProperty`.

So basically the project structures would be (for example) like this:
```
Central\Central.csproj
Central\src\Central.cs (physical source file to the project)
BridgeCentral\BridgeCentral.csproj
BridgeCentral\src\Central.cs (as a link to ../src/Central.cs)
BridgeCentral\src\CentralExtensions.cs (physical source file to the project)
```

In fact, as long as you keep the **BridgeCentral** separated from the native **Central** project (not in the same solution due to namespace conflicts!), you could just name **BridgeCentral** as **Central** and use it.

For instance, this could be possible by laying the projects in the filesystem like that:
```
NativeSolution\Central\Central.csproj
NativeSolution\Central\src\Central.cs
BridgeSolution\Central\Central.csproj
BridgeSolution\Central\src\Central.cs (links ..\..\NativeSolution\Central\src\Central.cs)
BridgeSolution\Central\src\CentralExtensions.cs
```

In case you have code in the **Native Central** project that should not make it to the Bridge version, you do likewise, for instance, with a **NativeSolution\Central\src\CentralExtensions.cs** and ensure you **won't** link that file to the Bridge project.

Bear in mind in this last setup, Bridge projects would only work if linked to the **Central.dll** built off **BridgeSolution\Central\Central.csproj**. Native should be linked only against the **NativeSolution\Central\Central.csproj**. And you can have NuGet packages to easily link or distribute your Central project, perhaps calling the packages as **Central-1.0.0.nupkg** to the native one and **Bridge.Central-1.0.0.nupkg** for the Bridge one.

One example of two NuGet packages for the very same namespace is for the Newtonsoft.Json port to  Bridge and the original one:
- Original: https://www.nuget.org/packages/Newtonsoft.Json/
- Bridge's: https://www.nuget.org/packages/Bridge.Newtonsoft.Json/
Both assemblies export the same namespace (`Newtonsoft.Json.*`).

I hope this clarifies the concept of code sharing. At least that's as far as I understand it should work.

**Comment by natiki** [comment]
@fabriciomurta Aaaaahhhhh now I see what you mean!!!! Ultimately even with partial classes you are still relying on the source linking. 

Many many thanks for the explanation I get it now. As luck would have it you mention JSON which is an issue I still have see #3846

I am going to close this one and suggest that this should become part of the Wiki as this is a clearer explanation than what is in there IMHO.

**Comment by fabriciomurta** [comment]
Well, the wiki entry does not really mean the same concept here so this would maybe be another wiki entry; in the wiki the Bridge project just merges in the code instead of making a completely independent Bridge.DTO library, which is the concept explored in the code above.

Your "aah" reaction was funny! I'm glad I could explain it better and it actually helped you understand the concept behind code reusage between projects!

You are welcome contributing to the project, if you happen to compile the information into a useful wiki post, you believe will help others beginning with Bridge, I believe you can "pull request" even a wiki entry here in github.

**Comment by fabriciomurta** [comment]
> Ultimately even with partial classes you are still relying on the source linking.

And yes, actually the classes have been turned partial especially to allow having both the linked and extension versions living in the project -- although it won't make much sense in the native project if it does not have specific code to that side, it'd open doors to arbitrarily extending and fine-tuning the class if there's any specifics (C# has a limitation where we can only [extend classes regarding methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) to non-partial classes -- or external assembly classes).
