### ISSUE TITLE
Any problems with circular references?

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3889]
In file `Translator.InspectAssembly.cs` in method `LoadAssembly` you have this code:
```
if (CurrentAssemblyLocationInspected.Contains(location))
            {
                var message = string.Format("There is a circular reference found for assembly location {0}. To avoid the error, rename your project's assembly to be different from that location.", location);

                this.Log.Error(message);
                throw new System.InvalidOperationException(message);
            }
```
this code was added in issue #2413

but why? i need this in my project :)
if you have some questions f.e. "why you need this", i'll answer later :) but .net can compile my code, but bridge can't

**Comment by fabriciomurta** [comment]
The short answer would be the same assembly (theoretically) can't exist twice in the same referencee assembly. Now, how you have a case that requires this to be allowed, and works without "hitchhicks" in native .NET, that'd be the million dollar question. :)

If you can share a minimalistic scenario where this is desirable we could either remove this code or create a project configuration trigger to ignore this test (a bridge.json/assemblyinfo/translate setting).

As you can see in issue #2413, our Mono.Cecil parser would loop up until all allocatable memory was exhausted. So perhaps instead of failing we could just use the one loaded/in cache using the feature you provided with #3805 instead of bloating up memory.

**Comment by colderlord** [comment]
example:
Assembly1 (depends on Assembly2)
```
public class Cross1
{
	public Cross2 Cross2 { get; set; }
}
```

Assembly2 (depends on Assembly1)
```
public class Cross2
{
	public Cross1 Cross1 { get; set; }
}
```


Assembly3 (depends on Assembly1)
```
public class TestClass
{
	public Cross1 Cross1 { get; set; }
}
```

When i tried to build Assembly3:
1. Throws compile error, because Assembly3 needed reference on Assembly2
2. When i will add reference on Assembly2 -> throws compile error "circular reference"

.net can build this, but bridge can't.

I change body of condition. instead of throwing error i return null, and bridge compiled my code

**Comment by colderlord** [comment]
any suggestions?

**Comment by geoffreymcgill** [comment]
Circular references are not supported by Bridge. It's something we hope to improve in the future, but for now, the functionality is not supported.
