### ISSUE TITLE
Blazor vs Bridge.net

### ISSUE THREAD

**Issue by j209** [bridgedotnet/Bridge#3928]
Hi
What is different between blazor and bridge?

**Comment by miladsadeghi72** [comment]
Blazor working by web assembly
Bridge working by javascript
Both is awesome, blazor is faster
But make apps by bridge is more logicaly

Bridge have retyped which can use any frameworks in c# bridge, angular, node js, and....

In other side blazor have own framework, something like react
In client side bridge is more flexable and more usable, because of javascript

This is all I know
However you must make a project by both to understand differents

**Comment by miladsadeghi72** [comment]
I Don't know

**Comment by geoffreymcgill** [comment]
Original response by @miladsadeghi72

Blazor working by web assembly
Bridge working by javascript
Both is awesome, blazor is faster
But make apps by bridge is more logicaly

Bridge have retyped which can use any frameworks in c# bridge, angular, node js, and....

In other side blazor have own framework, something like react
In client side bridge is more flexable and more usable, because of javascript

This is all I know
However you must make a project by both to understand differents

**Comment by adarisGmbH** [comment]
Blazor is a monolithic framework trying to address all developer concerns at once. Essentially, it extends the ASP.NET Razor syntax onto the client (web browser) by running the .NET runtime in the browser via the fairly new webassembly technology (wasm). So basically, Blazor assumes that you want to use everything they offer: Mono on WASM, Razor Syntax, their UI rendering engine, etc.

Bridge, on the other hand, ports a large portion of the .NET framework onto the browser via JavaScript. It is completely decoupled and independent from other technologies like UI / databinding frameworks. This makes it possible for you to run - for example - the popular Vue.js using C#! In other words, Bridge allows you to connect your most favorite technologies in the browser while doing so in C#.

Also, I like to point out:

- Mono for WASM is painfully slow in loading (due to missing ahead-of-time compilation)
- While supposedly "all major browser vendors" support WASM, I'd like to point out that pure JavaScript - and therefore Bridge - runs on billions of devices, even older ones like IE 9+.
- Bridge.NET has been developed and refined for about 5 years, while Blazor is just barely making it out of preview stage.

**Comment by hardhub** [comment]
What is about size of runtime and app for both?

Does anybody can provide some values?
