### ISSUE TITLE
Properties emitted UpperCamelCase and Fields lowerCamelCase by default

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#403]
The code
```csharp
public class MyClass
        {
            public string MyField;
            public string MyProperty { get; set; }
        }

        public static void MyFunction()
        {
            var myVar = new MyClass();
            myVar.MyField = "My field value";
            myVar.MyProperty = "My property value";

            Script.Write("console.log('MyField:'+myVar.My);");
            Script.Write("console.log('myField:'+myVar.myField);");
            Script.Write("console.log('MyProperty:'+myVar.MyProperty);");
            Script.Write("console.log('myProperty:'+myVar.myProperty);");
     }
```

produces in the browser's console:
```
MyField:undefined
myField:My field value
MyProperty:My property value
myProperty:undefined
```

This is at least misleading for users accessing fields and properties from JavaScript e.g. from external libraries.

This is specially true with AngularJS where variables are accessed thru `{{myVar.myField}}` or `{{myVar.MyField}}` and are case-sensitive.

Changing the case of the variable of properties will reflect on the auto-get/set methods generated by every property in a class (must follow the casing).

**Comment by DaniilVeriga** [comment]
As @vladsch stated in our internal discussion, that is by design:

 C# properties are rendered to private JavaScript properties and they have to be used in JavaScript via getter and setter only in JavaScript. If you want to emit an auto property as a field then use a `[FieldProperty]` attribute for a property. 

```[FieldProperty]
public string MyProperty { get; set; }```

In this case it will be emitted as a regular JavaScript field and you can use it as `myProperty`.

@fabriciomurta, do you think the issue can be closed and, maybe, change the "defect" label to "question"?

**Comment by fabriciomurta** [comment]
Sure, sure.
