### ISSUE TITLE
Array.IndexOf and Array.LastIndexOf are static and an instance member

### ISSUE THREAD

**Issue by evantobin** [bridgedotnet/Bridge#4033]
Within Bridge.Net, Array.IndexOf and Array.LastIndexOf are both static and instance methods. Within C#, they should only be static methods per Microsoft documentation: 

https://docs.microsoft.com/en-us/dotnet/api/system.array.lastindexof?view=netframework-4.8#System_Array_LastIndexOf_System_Array_System_Object_
https://docs.microsoft.com/en-us/dotnet/api/system.array.indexof?view=netframework-4.8#System_Array_IndexOf_System_Array_System_Object_

dotnetfiddle: https://dotnetfiddle.net/dIvnnB
deck.net: https://deck.net/91db4a801d1969d64d90674296d151b7

**Comment by evantobin** [comment]
Frameworks do not use this method as it's not expected to exist: https://github.com/bridgedotnet/Frameworks/search?q=IndexOf&unscoped_q=IndexOf

**Comment by fabriciomurta** [comment]
Cool, great job in investigating it!
Neither is Bridge.Newtonsoft.Json: https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/search?q=IndexOf&unscoped_q=IndexOf

**Comment by fabriciomurta** [comment]
Your contribution has just been merged upstream and will be part of our next Bridge release, pointed by the milestone we attached to this issue and the pull request.

It turned out our [Deck](https://deck.net/) project itself used this extraneous implementation. But the fix, as could be expected, was trivially rearranging the bits of the code around the line to turn the call the way it would work in native .NET.
