### ISSUE TITLE
Bridge 17.10.0 changes metadata file naming convention (breaking change if bridge.json resources file list used)

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge#4082]
Steps to reproduce:

1. Close all VS instances (this is a precautionary step, sometimes it seems like VS has problems having multiple versions of Bridge loaded simultaneously and I was having difficult reproducing this bug earlier today, so I did this to be really sure)
2. Open a new VS instance (I'm using 2019 16.3.0 Preview 4.0) and create a new .NET Framework Class Library named "BridgeMetadataFilenameTest.UI"
3. Add the Bridge NuGet package **version 17.9.0** (not latest!)
4. Without making any other changes, build the solution, wait for it to finish and then view the contents of bin/debug/bridge and note the presence of the file "BridgeMetadataFilenameTest.UI.meta.js"
5. Delete every file in this folder
6. Upgrade the Bridge NuGet package to 17.10.0 - this may ask you to restart VS, if it doesn't then I recommend restarting it anyway
7. Build the solution again, wait for it to finish and then view the contents of bin/debug/bridge and note the presence of the file "BridgeMetadataFilenameTest.meta.js" - the filename is different to what it was with Bridge 17.9.0, the ".UI" portion of the name is absent

This caused a problem for us because we have some libraries where we control which files that we include by using the "resources" file list in bridge.json and now the metadata files have the wrong names.

I tried to workaround the issue by using the reflection / output option to specify the filename to use but that does not work (see issue #4081).

**Comment by fabriciomurta** [comment]
Aren't you talking about #4010? That was an expected breaking change, unfortunately.

You may be interested in looking at [breaking changes for Bridge 17.10.0](https://github.com/bridgedotnet/Bridge/issues?utf8=%E2%9C%93&q=is%3Aclosed+milestone%3A17.10.0+label%3Abreaking-change). There's just another more.

**Comment by ProductiveRage** [comment]
@fabriciomurta erm.. I can't tell. I've read the issue you've linked and the reported fix but neither seem to mention a change to the filename structure in cases where there are no [Filename] attributes used. I couldn't immediately see any information that suggested that my metadata file names would change since I'm NOT using any such attributes.

**Comment by ChrML** [comment]
@geoffreymcgill @fabriciomurta I just discovered the same issue. This is regression. Unfortunately a critical regression for people that use punctum in project names. It is is not the expected breaking change due to #4010, it's a seperate issue.

The error occurs to all Bridge.NET projects that export metadata where the project name contains a dot (.). Example if you have a project called "Page.ResetPassword":

- Code will be written to `Page.ResetPassword.js` as expected
- Meta will be written to `Page.meta.js` which is not expected (previously `Page.ResetPassword.meta.js`)
- If you have multiple projects that begin with `Page.` then only the last compiled project will survive (file gets overwritten for each project compiled)

The same also occurs if the `FileName` attribute is used to export classes to multiple files. Take the following code:
`
[FileName("Test.Number1")]
class TestNumber1
{
  ...
}
`

Will output the following files:

- `Test.Number1.js`
- `Test.meta.js` (previously expected to be `Test.Number1.meta.js`, but due to #4010 it was instead output to the main `*.meta.js` file)

**Comment by geoffreymcgill** [comment]
Thanks for the reports. We are investigating and will try to fix right away.

**Comment by fabriciomurta** [comment]
We have fixed it not to trim text following dot in the class or namespace, however it is set to draw the file name as. We will do a hotfix release to include this correction.

**Comment by ChrML** [comment]
Seems to work correctly in 17.10.1. Thanks for quick fix!

**Comment by fabriciomurta** [comment]
Thanks for kindly giving us a feedback and confirmation of the fix!
