### ISSUE TITLE
Number Parse not working

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#541]
I'm trying to parse numbers but 1 comes up as 45.
![image](https://cloud.githubusercontent.com/assets/10186738/10831408/c972bff0-7e85-11e5-907c-822fbc9abc82.png)

**Comment by vladsch** [comment]
Thanks for your report. Can you you create C# sample which reproduces the issue?

**Comment by michaelcheers** [comment]
I think might be because of char.ToString();

This doesn't work
This gives me 50.
            string value = "";
            char toSetTo = (char)('1' + 1);
            value += toSetTo;
            Console.Log(value);

This Works
                 This gives me 2.
            string value = "";
            char toSetTo = (char)('1' + 1);
            value += toSetTo.ToString();
            Console.Log(value);

**Comment by vladsch** [comment]
Thanks for test case. The issue was already reported and fixed
Issue: https://github.com/bridgedotnet/Bridge/issues/538
Commit: https://github.com/bridgedotnet/Bridge/commit/95f7d71f77bab261e2b8318391f67d99bb3f033f
The pull request is not merged yet with master branch.

The fix will be included to upcoming 1.10 release
