### ISSUE TITLE
Implement basic <canvas> Element class

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#7]

**Comment by geoffreymcgill** [comment]
What is the status of this feature?

**Comment by fabriciomurta** [comment]
What? I mean, I thought this has already been implemented since I started working in canvasrenderingcontext2d (#8)! 

I really don't know now. What could be missing if I can already not only use the element but draw inside it? Maybe this just wasn't updated when done..

**Comment by DaniilVeriga** [comment]
Well, a basic &lt;canvas> Element class was implemented before the 1.0 release. 

But the issue was left open because of #8 which is stubbing out context classes. I am going to rename #8 adding "2D" in the title. I believe @fabriciomurta has already implemented it and, probably, #8 might be closed with 1.3 milestone.

As for WebGL I am going to create a separate issue, as well, I'll be committing in minutes.

As for the current issue, I think it should be also milestoned with 1.3, because a canvas element is not quite usable without rendering contexts. I will close this issue after committing WebGL.

**Comment by DaniilVeriga** [comment]
Ok, #8 and #189 are closed. From now on, we might consider a &lt;canvas> Element to be fully supported in Bridge. Closing the issue.
