### ISSUE TITLE
Support for piped and ampersand Enum parameters

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#707]
Syntax sample:

http://live.bridge.net/#c5220b85ff2ec788d461

```csharp
    public class App
    {
        [Ready]
        public static void Main()
        {
            DoSomething(Names.Multiline | Names.IgnoreCase);
        }

        public static void DoSomething(Names names) { }
    }

    public enum Names
    {
        Multiline,
        IgnoreCase
    }
```

Related forum discussion:

http://forums.bridge.net/forum/community/help/1225-controlling-what-gets-emitted-for-flags-enum

**Comment by vladsch** [comment]
According MSDN documentation you should set Flags attribute for enum and define enumeration constants in powers of two
https://msdn.microsoft.com/ru-ru/library/system.flagsattribute.aspx

Test case:
http://live.bridge.net/#4424ed1210ffef71a240

I will close the issue because the functionality is already supported
