### ISSUE TITLE
System.Diagnostics.Debug support

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#718]
A feature request has appeared in [this comment](https://github.com/bridgedotnet/Bridge/issues/625#issuecomment-157384864) of #625.

It is already in Bridge 2.0. @geoffreymcgill, do you think it is going to appear in Bridge v1 ever?

**Comment by DaniilVeriga** [comment]
Added in #887.

**Comment by t-nelis** [comment]
@DaniilVeriga Use of `confirm` & `debugger` for `Assert` is a really nice touch (I would've expected a quick & dirty `console.assert`, but you're definitely doing things properly!).

~~Note: I haven't actually tested it (though it seems rather straightforward) as the latest master head (f802a4c4acb6ef19ac5e54afe42520606ebf683c) doesn't build without giving it a little bit of love (something about~~

I figured it out (can't help myself can I?); the local git repository directory *must* be named "Bridge", which is a little bit obscure as build requirements go. I don't know if I'm alone doing this, but sometimes I name clones arbitrarily for organization or consistency purposes. It's probably not important, but it was confusing at first.

So, I tried out everything in `Diagnostics.*` (all methods, and observed them being stripped in release builds); works perfectly. Thanks!

(Didn't test `Contracts.*`, but now that you support them, we just might.)

**Comment by DaniilVeriga** [comment]
@t-nelis, thank you very much for the feedback! Very happy to hear that `System.Diagnostics.*` goes well on your end.

As for building from sources, first of all, we are sorry for the inconvenience. Is "Bridge" name really required? I did a quick test and seems could not reproduce the issue. Well, I probably did something wrong. Anyways, please note there is the [Build From Sources](http://bridge.net/kb/build-from-source/) knowledge base article. **But** it is currently out-date. Initially it missed some key point (#731) and recently the build process has been significantly revised-improved-cleaned. So, the knowledge base article is awaiting for the revision as well. It is going to happen just after the 1.11 release.

**Comment by t-nelis** [comment]
@DaniilVeriga Hold off on any head-scratching repro attempts, I can't repro again either (I can now build from an arbitrarily named repository directory).

For reference I suppose I'll document what I can remember in case it pops up again, but I don't think it warrants a follow-up:

I didn't know about the KB article. It's easy to find, I just didn't go look for it there and sort of winged it. So starting from f802a4c I looked at both the `Bridge.sln` and `Bridge.Builder.sln` solutions. The Builder solution contains references to some projects that fail to load.

```
C:\Users\tne\src\bridge\Compiler\Build\Bridge.Build.csproj : error  : The imported project "C:\Users\tne\src\bridge\Compiler\.build\NuGet.Build.Package.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\tne\src\bridge\Compiler\Build\Bridge.Build.csproj
C:\Users\tne\src\bridge\Compiler\Contract\Bridge.Contract.csproj : error  : The imported project "C:\Users\tne\src\bridge\Compiler\.build\NuGet.Build.Package.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\tne\src\bridge\Compiler\Contract\Bridge.Contract.csproj
C:\Users\tne\src\bridge\Compiler\Translator\Bridge.Translator.csproj : error  : The imported project "C:\Users\tne\src\bridge\Compiler\.build\NuGet.Build.Package.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\tne\src\bridge\Compiler\Translator\Bridge.Translator.csproj
```

I thus focused on `Bridge.sln`, quickly checked the `README` and `CONTRIBUTING` files and looked for a `BUILD`, `INSTALL` or `HACKING` file for possible instructions (maybe you could add a link to the KB article somewhere there if more "passerby contributors" do this).

Attempting to build the solution fails because the client projects cannot restore NuGet packages. For example:

`NuGet Package restore failed for project Testing\client: Unable to find version '1.0.0' of package 'Bridge.Collections.Dev'..`

I then unloaded the test projects, switched to release mode and hoped the build system doesn't depend on running tests for release targets. *At this point* it builds fine. I also quickly found your helpful `collect-nuget-packages.bat` script, setup a NuGet source and went on to testing in an arbitrary project.

But *earlier today* I was still hitting an error even after disabling the test projects. If memory serves, `.build/NuGet.Build.Package.targets` complained around line 80+ (I'm fairly sure the exec command at line 86) about not finding "part of path ..." (so that would be `NuGetPackageOutputDir`). The path in question started with `C:\Users\tne\src\Bridge\Bridge\build\...`. I spotted that it wasn't the actual path of my repository, so I renamed it to match the expected path, built successfully and striked through my earlier comment.

I assumed it was because the repo directory name was hardcoded somewhere and called it a day, but looking at L63:

`      <NuGetPackageOutputDir Condition="$(NuGetPackageOutputDir) == '' Or $(NuGetPackageOutputDir) == '*Undefined*'">$(ProjectDir)$(OutDir)</NuGetPackageOutputDir>`

I now think it wasn't your fault: probably some VS/MSBuild idiosyncrasies around how `ProjectDir` is defined. I can't swear it, but I might have renamed the repo directory some time after opening the solution for the first time a long while ago (so it could be that VS recorded the old name somewhere and the oldname might have been the expected path). I did a few `git clean -xdf` runs after the build failed to make sure I had a pristine working space though, so that's still a little weird. Maybe I didn't reload the solution right or something.

**Comment by DaniilVeriga** [comment]
Thank you for the comprehensive feedback on this topic. Confirm - currently, building from sources are hackish. Again, we apologize for the inconvenience. Unfortunately, we could not revise the build process in one step. So, it is currently in between. All these issues should pass away very soon.

**Comment by LeonidVeriga** [comment]
`Bridge.Builder.sln` is an old solution file and will be removed.

Yes, please use new **Bridge.sln**. We are in the process of enhahcing the testing approach. And at the moment it requires unloading projects in **Testing** folder.

**Comment by DaniilVeriga** [comment]
I don't see `Bridge.Builder.sln` in the repo:
https://github.com/bridgedotnet/Bridge

Probably, it was somehow left on your end after a pull.

**Comment by t-nelis** [comment]
@DaniilVeriga It's under `/Compiler`.

**Comment by DaniilVeriga** [comment]
Ah, indeed. Thank you for the pointer!
https://github.com/bridgedotnet/Bridge/tree/master/Compiler

**Comment by geoffreymcgill** [comment]
Building from source has been simplified in the current **master** branch and these changes will be shipped with Bridge 1.11. 

To create a NuGet package, now all you have to do is compile the Bridge Solution in Release mode. The **.nupkg** files will be automatically created and added to the **/bin/Release/** folder of each project. 

Hope this helps.

**Comment by t-nelis** [comment]
@geoffreymcgill Nice and easy. I tried building all packages, including those from `Frameworks`, then used the `collect.bat` script to setup a NuGet source with all of them (I assume that's the intent). *I'll note here that the script does expect specific names for the directories of the repositories (Bridge and Frameworks respectively) -- for real this time! (No big deal.)*

Both solutions are straightforward to build in release mode, with the only exception of the testing projects which still need to be disabled. Now that I actually setup the proper NuGet source I thought I would be good to go; but I can't seem to find the `Bridge.Test` implementation anywhere.

Looking at the `collect.bat` script again it looks like there ought to be a `Test` repository somewhere with a `Bridge.Test` project inside. It's not on GH though, and `Testing` doesn't seem to be it. Is it internal/private? (It'd be nice to be able to run the tests in order to contribute.)

```
:: Bridge.Test
echo f | xcopy /f /y "%root%Test\Bridge.Test\bin\%build%\*.nupkg"               %output%
```

**Comment by geoffreymcgill** [comment]
@t-nelis: At the moment **Bridge.Test** is not publicly available, but we hope to release soon. For now the only option is to unload everything within the *Tests* folder from the Solution. 

Right-click on the **Tests* folder and select **Unload Projects in Solution Folder**. Then compile in `Release` mode. 

<img width="392" alt="screenshot 2016-02-16 09 13 09" src="https://cloud.githubusercontent.com/assets/62210/13082352/95f9456e-d48d-11e5-8d45-636491480439.png">

Hope this helps.

**Comment by t-nelis** [comment]
@geoffreymcgill Thanks for the clarification. Looking forward to it.
