### ISSUE TITLE
Revise "undefined" concept

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#782]
http://forums.bridge.net/forum/general/open-discussions/1320

> "undefined" is a strange concept in C#. Having it map to "null" would be easier to deal with.

**Comment by johnwason** [comment]
After looking at the problem more I am not sure what I suggested makes sense. Maybe have a utility method IsNullOrUndefined somewhere?

**Comment by SamuelEnglard** [comment]
A thought would be to map `undefined` to a "class", something like

````csharp
public static class Undefined
{
    private static readonly object _internal = new object();

    public static object Undefined
    {
        get
        {
            return _internal;
        }
    }
}
````

So `Undefined.Undefined` compiles down to just `undefined`

**Comment by johnwason** [comment]
Currently there is the definition "Script.undefined" that can be used to compare to "undefined".  This leads to a lot of code:

    if (myvar == null || myvar == Script.undefined)
    {
        //Do something to deal with unset variable
    }

I think that this is what you suggest. Maybe replace the comparison with a utility function:

    if (Script.IsNullOrUndefined(myvar))

**Comment by SamuelEnglard** [comment]
Ah, yes. In that case I think such a utility function could work. Though I think I might make it an extension method on `Object`

**Comment by geoffreymcgill** [comment]
I like the idea of an extension method on `Object`, although I'm a little reluctant to be bolting on unexpected members to native classes. 

The *Script* class might also get separated out into the *Html5* project with v1.11, and since `undefined` is not a C# concept, all references to `undefined` within the main *Bridge* project will likely be moved to *Html5* as well.

I'm just speculating here, and haven't taken a really good look at the implications of this reorganization. Once we get in there (this week) we'll have a better understanding of what needs to change.

Thanks for the great feedback and comments.

**Comment by Suchiman** [comment]
@johnwason there's `Validation.IsNotNull()` which is basically defined as `typeof value !== "undefined" && value !== null;`

But i agree that undefined is currently being handled awkwardly.

**Comment by DaniilVeriga** [comment]
With the upcoming 1.11 release `obj === null` check will be emitted as `!Bridge.hasValue(obj)` that actually checks on both - `null` and `undefined`. We will appreciated any feedback.
