### ISSUE TITLE
Problem awaiting a dynamic variable

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#918]
Awaiting a dynamic variable does not generate "taskResult".  For instance:

        dynamic a = new App() as dynamic;
        Console.WriteLine((int)await a.Test());

emits

        $task1.getResult();
        console.log(Bridge.cast($taskResult1, Bridge.Int));

when it should be

        $taskResult1=$task1.getResult();
        console.log(Bridge.cast($taskResult1, Bridge.Int));

http://live.bridge.net/#bef4a120fffb2fba2eaf

**Comment by vladsch** [comment]
Compiler doesn't know return type of Test method because it is dynamic method. So, you need to cast Test invocation, also Bridge doesn't change case for dynamic code (Test will be emitted as is, like "Test", not "test")

So, you shoud use
`Console.WriteLine((int)await (Task<int>)a.test());`

**Comment by johnwason** [comment]
Would it be possible to implicitly detect when a return value is expected?  This works in standard C# without a cast and I think it will confuse the users of my library to have to cast before the await.

**Comment by vladsch** [comment]
yes, we will try to fix it. Thanks for your test case

**Comment by vladsch** [comment]
It will be fixed in 1.11
Just please note that Bridge doesn't change case of dynamic code because compiler doesn't know about type of dynamic expression (it can be type reference or method)
So, if you write dynamic code then you should pay attention on case of the code

For example, `await a.Test()` will not work because real `Test` method is emitted as `test`. Therefore you should use lower case also in dynamic expression `await a.test()`

**Comment by vladsch** [comment]
Also, using dynamic awaiter is not good idea because we have no type information during compilation. So, we cannot get information about how to get awaiter (for dynamic code we assume that it is Task). But awaitable object can be any object which has GetAwaiter method (or extension method). In this case, Bridge will not able to get info about such methods. 
It is better if Bridge will throw an exception if dynamic code is used as awaiter (not in v1 but in v2) because it is easy to get incorrect javascript

**Comment by johnwason** [comment]
This test case fails with #924 but works with #925:

    public class App
    {
        public async Task<int> test()
        {
            return 1;
        }
    

        [Ready]
        public static async void Main()
        {
            dynamic a = new App() as dynamic;
            await a.test();
            var c = await a.test();
            Console.WriteLine((int)await a.test());
            App b = new App();
            await b.test();            
        }
    }

**Comment by johnwason** [comment]
Also, I forgot to put rr2!=null in the "if" statement in my version. It should be:

var awaiterMethod2 = rr.GetAwaiterInvocation as DynamicInvocationResolveResult;
                    if (rr2 != null && !(unaryExpr.Parent.Role is ICSharpCode.NRefactory.Role<ICSharpCode.NRefactory.CSharp.Statement>))
                    {                        
                        return true;
                    }

**Comment by johnwason** [comment]
Nevermind, there was a problem with my test.  Thanks for fixing this issue!
