### ISSUE TITLE
Keys in dictionary are returned in sorted order

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#962]
## See Also

* http://forums.bridge.net/forum/bridge-net-pro/bugs/1559

**Comment by DaniilVeriga** [comment]
@geoffreymcgill, please change the milestone if it is not meant to go to 1.11.

**Comment by geoffreymcgill** [comment]
I would like to try and fix for 1.11.

**Comment by michaelcheers** [comment]
Why when you have a dictionary with keys, say

a
abc
acb
b,

you get a, b, abc then acb.

**Comment by geoffreymcgill** [comment]
@michaelcheers: As mentioned in the related forum thread, the current implementation of Dictionary in Bridge is correct, although the result is unexpected when compared to native C#. 

We're investigating a change to the Bridge logic, although only if it requires very little additions to **bridge.js** to make this work. 

The order of the Dictionary keys is non-deterministic. Do not rely on the keys returning in the order they were added.

**Comment by fabriciomurta** [comment]
I think the internal ordering should not be considered or tagged as a defect if we are talking about Dictionary. It is meant to be fast and to get the keys the fastest way possible in the current language implementation. To attain best performance different hash algorithms may be used to the dictionary, depending on the language, and this may or may not include sorting in the process.

A sorted list indicates that recovering entries should be pretty fast as when searching the list, given the current element, the program can know whether to go forward or backwards looking for the desired one. Probably in c# the hashset implementation used by dictionaries (I didn't look at it in detail) uses some level of sorting in their hash chunks. It just happened that in JavaScript the array itself is sorted in favor of the dictionary.

That said I believe this only should be considered for fixing or review/improving if the current implementation is arguably slow. The list being ordered in the case does not suggest a bad organization or unnecessary overhead though, but the other way around. And given the performance of JavaScript can be much slower than a compiled C# application due to its interpreted nature, it is not enough to just prove C# uses a different approach on dictionary, cause it probably can simply not fit the JavaScript structure. One way to prove the current dictionary implementation is slow could be with another JavaScript dictionary implementation. I don't think this has ever been the point of this issue though.

I'm just sharing my opinion on the issue.

**Comment by michaelcheers** [comment]
@DaniilVeriga, @geoffreymcgill, @vladsch, is there any hope of this being fixed for 16.0?

**Comment by michaelcheers** [comment]
I made a pull request: #2858.
