### ISSUE TITLE
Bridge Live isn't Working

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#986]
[Behaviour](http://live.bridge.net/#80610ead463446e803f9)

### Expected behaviour

Compile Successfully.

### Actual behaviour

Not Compile with error:
// Line 0, Col 0 : Failed to compare two elements in the array.

### Steps to reproduce the behaviour

Just try to compile.

**Comment by geoffreymcgill** [comment]
There are a couple issues going on here. 

The first is, the `Alert` Method accepts a *string* object, and you are passing an *int*. If you convert `x` to a *string* by calling `.ToString(), then it will compile correctly. 

```csharp
Global.Alert(default(Example).x.ToString());
```

The second issue likely has something to do with the 1.10.4 release. Running your code (with call to `.ToString()`) in the latest code from *master* branch is working.

We will try to track down the issue that was fixed after 1.10.4 release which enabled this scenario, although it does appear to be fixed in the next release.
